// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Arcmira from "../../../../../index.js";

export declare namespace RecommendationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class RecommendationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RecommendationsClient.Options>;

    constructor(options: RecommendationsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Cursor-paginated commercial mentions (ad reads, endorsements, neutral mentions) for one entity, newest media first. The signed continuation binds the route, filters, limit, caller and visibility; invalid or old cursors return invalid_cursor. A first-page ID fence excludes later insertions, including old-date backfills. Edits and deletions to existing rows remain live. Requires a Pro+ plan. Read timestamps from start_seconds / end_seconds (integer seconds); the MM:SS string fields are deprecated. Rows below min_confidence (default 0.7) and disputed rows (unless include_disputed=true) are excluded.
     *
     * @param {Arcmira.entities.ListRecommendationsRequest} request
     * @param {RecommendationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.entities.recommendations.list({
     *         id: "id"
     *     })
     */
    public async list(
        request: Arcmira.entities.ListRecommendationsRequest,
        requestOptions?: RecommendationsClient.RequestOptions,
    ): Promise<core.Page<Arcmira.Recommendation, Arcmira.RecommendationListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Arcmira.entities.ListRecommendationsRequest,
            ): Promise<core.WithRawResponse<Arcmira.RecommendationListResponse>> => {
                const {
                    id,
                    limit,
                    cursor,
                    channel_id: channelId,
                    channel_name: channelName,
                    mention_class: mentionClass,
                    min_confidence: minConfidence,
                    date_from: dateFrom,
                    date_to: dateTo,
                    include_disputed: includeDisputed,
                    src,
                } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    channel_id: channelId,
                    channel_name: channelName,
                    mention_class: mentionClass != null ? mentionClass : undefined,
                    min_confidence: minConfidence,
                    date_from: dateFrom,
                    date_to: dateTo,
                    include_disputed: includeDisputed,
                    src: src != null ? src : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ArcmiraEnvironment.Default,
                        `v1/entities/${core.url.encodePathParam(id)}/recommendations`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Arcmira.RecommendationListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Arcmira.BadRequestError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Arcmira.UnauthorizedError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 402:
                            throw new Arcmira.PaymentRequiredError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Arcmira.ForbiddenError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Arcmira.NotFoundError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Arcmira.TooManyRequestsError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Arcmira.InternalServerError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ArcmiraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/entities/{id}/recommendations",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Arcmira.Recommendation, Arcmira.RecommendationListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next_cursor != null &&
                !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
            },
        });
    }
}
