// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../../../index.js";

/**
 * @example
 *     {
 *         slug: "slug"
 *     }
 */
export interface OrganizationsRelatedRequest {
    /** The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it. */
    slug: string;
    limit?: number;
    /** Opaque cursor from a previous page's next_cursor. */
    cursor?: string;
    /** Substring filter over the row's text columns (e.g. video title, channel name, description). */
    q?: string;
    /** Restrict the q filter to one column. Default "any" (all searchable columns). */
    field?: string;
    /** Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel"). */
    sort?: string;
    /** Sort direction. Default desc. */
    order?: Arcmira.organizations.OrganizationsRelatedRequestOrder;
}
