// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListRecommendationsRequest {
    limit?: number;
    /** Signed continuation from next_cursor. Bound to this route, normalized query, caller and visibility; invalid or old tokens return invalid_cursor. */
    cursor?: string;
    entity_id?: string;
    entity_name?: string;
    entity_type?: Arcmira.ListRecommendationsRequestEntityType;
    channel_id?: string;
    channel_name?: string;
    mention_class?: Arcmira.ListRecommendationsRequestMentionClass;
    min_confidence?: number | null;
    date_from?: string;
    date_to?: string;
    include_disputed?: boolean;
    /** The surface making this call. The Arcmira MCP server sends mcp-tool so every unlock link in a gate attributes to the directory install. Omit from your own client. */
    src?: Arcmira.ListRecommendationsRequestSrc;
}
