// This file was auto-generated by Fern from our API Definition.

export const ListMentionsRequestDetails = {
    Full: "full",
} as const;
export type ListMentionsRequestDetails = (typeof ListMentionsRequestDetails)[keyof typeof ListMentionsRequestDetails];
