// This file was auto-generated by Fern from our API Definition.

/** captions reads creator or automatic captions at 1 row per started 15 minutes. premium is one read: an owned transcript returns 200 state ready at zero rows; otherwise the read buys the whole video within the account's plan and on-demand budget (included credits first, then on-demand money up to the account limit) and returns 202 state pending with the job until it is ready. When the last purchase for the video failed it answers 200 state failed and buys again only with retry=true. 402 quota_exceeded or spend_limit_exceeded and 403 paid_plan_required carry the price in quote. It never substitutes captions. Default captions unless changed in account settings. */
export const GetTranscriptsRequestQuality = {
    Captions: "captions",
    Premium: "premium",
} as const;
export type GetTranscriptsRequestQuality =
    (typeof GetTranscriptsRequestQuality)[keyof typeof GetTranscriptsRequestQuality];
