// This file was auto-generated by Fern from our API Definition.

/** captions reads creator or automatic captions at 1 row per started 15 minutes. premium is read-only: an owned transcript returns 200 at zero rows, an active purchase returns 202 with status_url and next_poll_seconds, and an unowned transcript returns 403 purchase_required with quote_url and prepare_url. It never purchases or substitutes captions. Quote and explicitly purchase the whole video before reading Premium. Default captions unless changed in account settings. */
export const GetTranscriptsRequestQuality = {
    Captions: "captions",
    Premium: "premium",
} as const;
export type GetTranscriptsRequestQuality =
    (typeof GetTranscriptsRequestQuality)[keyof typeof GetTranscriptsRequestQuality];
