// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         feedback_id: "feedback_id"
 *     }
 */
export interface GetFeedbackRequest {
    /** The feedback submission id POST /v1/feedback returned, fbk_ and digits. */
    feedback_id: string;
}
