// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface LookupEntitiesRequest {
    id?: string;
    name?: string;
    type?: Arcmira.LookupEntitiesRequestType;
}
