// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../index.js";

/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface ResolveEntitiesRequest {
    /** A name, @handle, YouTube URL or channel id (UC...). One thing per call. */
    q: string;
    /** Restrict candidates to one type. Pass channel for a show and read best.youtube_channel_id. */
    type?: Arcmira.ResolveEntitiesRequestType;
    /** Candidates to return, 1 to 15. Default 8. */
    limit?: number;
    /** What the user said about the name, in their words ("the startup bank", "Canada's prime minister", "on My First Million"). Ranks candidates by their description and by the episodes they share with what the context names; a clear winner comes back as suggested with reason context. */
    context?: string;
    /** The surface making this call. The Arcmira MCP server sends mcp-tool so every unlock link in a gate attributes to the directory install. Omit from your own client. */
    src?: Arcmira.ResolveEntitiesRequestSrc;
}
