// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Arcmira from "../../../../../index.js";

export declare namespace MentionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MentionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MentionsClient.Options>;

    constructor(options: MentionsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Cursor-paginated mentions for one entity, newest media first. Read timestamps from start_seconds / end_seconds (integer seconds; 0 means full episode); the MM:SS (or HH:MM:SS) string fields are deprecated. is_appearance filtering applies to person entities only; passing is_appearance=true for any other type returns a 400 (appearances_person_only). details=full attaches per-mention commercial recommendations and requires a Pro+ plan.
     *
     * @param {Arcmira.entities.ListMentionsRequest} request
     * @param {MentionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.entities.mentions.list({
     *         id: "id"
     *     })
     */
    public async list(
        request: Arcmira.entities.ListMentionsRequest,
        requestOptions?: MentionsClient.RequestOptions,
    ): Promise<core.Page<Arcmira.Mention, Arcmira.MentionListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Arcmira.entities.ListMentionsRequest,
            ): Promise<core.WithRawResponse<Arcmira.MentionListResponse>> => {
                const {
                    id,
                    limit,
                    cursor,
                    channel_id: channelId,
                    channel_name: channelName,
                    q,
                    sentiment,
                    is_appearance: isAppearance,
                    date_from: dateFrom,
                    date_to: dateTo,
                    details,
                    src,
                } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    channel_id: channelId,
                    channel_name: channelName,
                    q,
                    sentiment: sentiment != null ? sentiment : undefined,
                    is_appearance: isAppearance,
                    date_from: dateFrom,
                    date_to: dateTo,
                    details: details != null ? details : undefined,
                    src: src != null ? src : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ArcmiraEnvironment.Default,
                        `v1/entities/${core.url.encodePathParam(id)}/mentions`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return { data: _response.body as Arcmira.MentionListResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Arcmira.BadRequestError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Arcmira.UnauthorizedError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 402:
                            throw new Arcmira.PaymentRequiredError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Arcmira.ForbiddenError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Arcmira.NotFoundError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Arcmira.TooManyRequestsError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Arcmira.InternalServerError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ArcmiraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/entities/{id}/mentions",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Arcmira.Mention, Arcmira.MentionListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next_cursor != null &&
                !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
            },
        });
    }
}
