// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         trackerIds: ["trackerIds"]
 *     }
 */
export interface AddTrackersRequest {
    /** Monitor id. */
    id: string;
    /** Ids of existing trackers ("trk_...") to attach to this monitor. Create trackers first via POST /v1/trackers. */
    trackerIds: string[];
}
