// This file was auto-generated by Fern from our API Definition.

/** Sort direction. Default desc. */
export const PeopleRelatedRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type PeopleRelatedRequestOrder = (typeof PeopleRelatedRequestOrder)[keyof typeof PeopleRelatedRequestOrder];
