// This file was auto-generated by Fern from our API Definition.

/** Person relationship lens: guest appearances or inbound mentions. */
export const ProductsRelatedRequestMode = {
    Appearances: "appearances",
    Mentions: "mentions",
} as const;
export type ProductsRelatedRequestMode = (typeof ProductsRelatedRequestMode)[keyof typeof ProductsRelatedRequestMode];
