// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         video_id: "video_id",
 *         sourceName: "sourceName",
 *         targetEntityId: 1
 *     }
 */
export interface SubmitMergesRequest {
    /** YouTube video id, 11 characters. */
    video_id: string;
    /** Persist a unique key and the exact request before sending a logical mutation. A retry returns its stored response with Idempotency-Replayed: true. A changed intent under a finalized key returns 409 idempotency_conflict. Keys belong to the authenticated owner, credential and mutation domain. Current authorization still applies. Receipts have no general 24-hour expiry; signing-secret recovery alone expires after 24 hours or when the secret is displaced. */
    "Idempotency-Key"?: string;
    /** The name as it appears in this video (e.g. a first-name-only mention). */
    sourceName: string;
    /** The canonical entity these mentions actually refer to. */
    targetEntityId: number;
    /** Optional respelling applied to the transcript text (e.g. "Imad" → "Emad"). */
    replaceWith?: string;
    revision?: string;
}
