// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         video_id: "video_id",
 *         sourceName: "sourceName",
 *         targetEntityId: 1
 *     }
 */
export interface SubmitMergesRequest {
    /** YouTube video id, 11 characters. */
    video_id: string;
    /** The name as it appears in this video (e.g. a first-name-only mention). */
    sourceName: string;
    /** The canonical entity these mentions actually refer to. */
    targetEntityId: number;
    /** Optional respelling applied to the transcript text (e.g. "Imad" → "Emad"). */
    replaceWith?: string;
    revision?: string;
}
