// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ListMentionsRequest {
    /** Entity id, ent_{n} or the numeric id. Merged ids follow their redirect. */
    id: string;
    limit?: number;
    cursor?: string;
    channel_id?: string;
    channel_name?: string;
    q?: string;
    sentiment?: Arcmira.entities.ListMentionsRequestSentiment;
    is_appearance?: boolean;
    date_from?: string;
    date_to?: string;
    details?: Arcmira.entities.ListMentionsRequestDetails;
}
