// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Arcmira from "../../../index.js";

export declare namespace EntitiesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EntitiesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EntitiesClient.Options>;

    constructor(options: EntitiesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Call this before passing an id to about, by, entity_ids, channel_ids or channel; those filters refuse names with id_required. Pass context with the user's own words about the name ("the startup bank", "on My First Million"). The answer is one of three: best (the name means one row: use it and name it), suggested (no row is certain but one stands out, with reason and evidence: use it and tell the user you assumed it), or ask (several rows fit: show ask.options, or check every option id and answer per row). For a show pass type=channel and use the youtube_channel_id; for a brand or a person use the id. Free; bills no rows.
     *
     * @param {Arcmira.ResolveEntitiesRequest} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.entities.resolve({
     *         q: "q"
     *     })
     */
    public resolve(
        request: Arcmira.ResolveEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Arcmira.EntityResolveResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resolve(request, requestOptions));
    }

    private async __resolve(
        request: Arcmira.ResolveEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Arcmira.EntityResolveResponse>> {
        const { q, type: type_, limit, context } = request;
        const _queryParams: Record<string, unknown> = {
            q,
            type: type_ != null ? type_ : undefined,
            limit,
            context,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ArcmiraEnvironment.Default,
                "v1/entities/resolve",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Arcmira.EntityResolveResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Arcmira.BadRequestError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 401:
                    throw new Arcmira.UnauthorizedError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 403:
                    throw new Arcmira.ForbiddenError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 404:
                    throw new Arcmira.NotFoundError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 429:
                    throw new Arcmira.TooManyRequestsError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Arcmira.InternalServerError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ArcmiraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/entities/resolve");
    }

    /**
     * Returns the canonical entity envelope for an ent_{n} or numeric id, following merge redirects. For organization and product entities, callers with Recommendations API access (a Pro+ plan) also receive a recommendations_summary commercial-intelligence rollup when a brand profile exists.
     *
     * @param {Arcmira.GetEntitiesRequest} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.entities.get({
     *         id: "id"
     *     })
     */
    public get(
        request: Arcmira.GetEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Arcmira.EntityDetailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Arcmira.GetEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Arcmira.EntityDetailResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ArcmiraEnvironment.Default,
                `v1/entities/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Arcmira.EntityDetailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Arcmira.BadRequestError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 401:
                    throw new Arcmira.UnauthorizedError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 402:
                    throw new Arcmira.PaymentRequiredError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Arcmira.ForbiddenError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 404:
                    throw new Arcmira.NotFoundError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 429:
                    throw new Arcmira.TooManyRequestsError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Arcmira.InternalServerError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ArcmiraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/entities/{id}");
    }

    /**
     * Mentions in the last 7 and 30 days against the prior 30, an absolute-delta verdict (accelerating, flat, fading, none), the newest media date, and the top shows in the window. It counts the shows we index, not the whole internet, and it is a count, not a score. On a Pro+ plan the card also carries paid_vs_organic; otherwise that field is absent and access names the gate. Bills one row. Every gate is a typed error whose error.unlock.url names the plan that lifts it; pass src=mcp-tool only from the Arcmira MCP server.
     *
     * @param {Arcmira.MomentumEntitiesRequest} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.entities.momentum({
     *         id: "id"
     *     })
     */
    public momentum(
        request: Arcmira.MomentumEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Arcmira.EntityMomentumResponse> {
        return core.HttpResponsePromise.fromPromise(this.__momentum(request, requestOptions));
    }

    private async __momentum(
        request: Arcmira.MomentumEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Arcmira.EntityMomentumResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ArcmiraEnvironment.Default,
                `v1/entities/${core.url.encodePathParam(id)}/momentum`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Arcmira.EntityMomentumResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Arcmira.BadRequestError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 401:
                    throw new Arcmira.UnauthorizedError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 402:
                    throw new Arcmira.PaymentRequiredError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Arcmira.ForbiddenError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 404:
                    throw new Arcmira.NotFoundError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 429:
                    throw new Arcmira.TooManyRequestsError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Arcmira.InternalServerError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ArcmiraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/entities/{id}/momentum");
    }
}
