// This file was auto-generated by Fern from our API Definition.

/** The surface making this call. The Arcmira MCP server sends mcp-tool so every unlock link in a gate attributes to the directory install. Omit from your own client. */
export const ListSponsorsRequestSrc = {
    McpTool: "mcp-tool",
} as const;
export type ListSponsorsRequestSrc = (typeof ListSponsorsRequestSrc)[keyof typeof ListSponsorsRequestSrc];
