// This file was auto-generated by Fern from our API Definition.

/** Person relationship lens: guest appearances or inbound mentions. */
export const PeopleRelatedRequestMode = {
    Appearances: "appearances",
    Mentions: "mentions",
} as const;
export type PeopleRelatedRequestMode = (typeof PeopleRelatedRequestMode)[keyof typeof PeopleRelatedRequestMode];
