// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetTranscriptionsRequest {
    /** Transcription request id, the UUID POST /v1/transcriptions returned. */
    id: string;
}
