// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface SubmitTranscriptionsRequest {
    /** YouTube video id (11 characters). Either videoId or url is required. */
    videoId?: string;
    /** A YouTube watch/short/live URL. Either videoId or url is required. */
    url?: string;
}
