// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
 *         id: "id"
 *     }
 */
export interface AddEntitiesRequest {
    /** Monitor id. */
    id: string;
    /** One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation. */
    "Idempotency-Key"?: string;
    /** Entity ids ("ent_...") to follow in this monitor, from GET /v1/entities/resolve or search. Duplicates count once. A merged id follows its redirect to the canonical entity. */
    entity_ids?: string[];
    /** Exact names to follow in this monitor, for a name not yet indexed or one you have no id for. The tracker is created in the monitor's account and attached in the same call; the account's tracker for the same name (compared case-insensitively) and type is reused. Duplicates count once. */
    names?: AddEntitiesRequest.Names.Item[];
    /** For person trackers this request creates: mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Other types ignore it, and a tracker that already exists keeps its own setting (change it with PATCH /v1/trackers/{id}). */
    person_match_mode?: AddEntitiesRequest.PersonMatchMode;
}

export namespace AddEntitiesRequest {
    export type Names = Names.Item[];

    export namespace Names {
        export interface Item {
            /** The exact name to watch, matched case-insensitively against analyzed media, so it can be followed before the entity is indexed. For a channel, the YouTube channel id (UC plus 22 characters); a channel name answers 400 id_required naming GET /v1/entities/resolve?q=...&type=channel. */
            name: string;
            /** person, organization (org is accepted), product, topic or channel. */
            type: Item.Type;
            /** For a person tracker this request creates; defaults to the top-level person_match_mode. Other types ignore it. */
            person_match_mode?: Item.PersonMatchMode | undefined;
        }

        export namespace Item {
            /** person, organization (org is accepted), product, topic or channel. */
            export const Type = {
                Person: "person",
                Organization: "organization",
                Org: "org",
                Product: "product",
                Topic: "topic",
                Channel: "channel",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            /** For a person tracker this request creates; defaults to the top-level person_match_mode. Other types ignore it. */
            export const PersonMatchMode = {
                Mentions: "mentions",
                Appearances: "appearances",
                Both: "both",
            } as const;
            export type PersonMatchMode = (typeof PersonMatchMode)[keyof typeof PersonMatchMode];
        }
    }

    /** For person trackers this request creates: mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Other types ignore it, and a tracker that already exists keeps its own setting (change it with PATCH /v1/trackers/{id}). */
    export const PersonMatchMode = {
        Mentions: "mentions",
        Appearances: "appearances",
        Both: "both",
    } as const;
    export type PersonMatchMode = (typeof PersonMatchMode)[keyof typeof PersonMatchMode];
}
