// This file was auto-generated by Fern from our API Definition.

/** For person appearances, true lists guest episodes and false lists inbound mentions. */
export const PeopleRelatedRequestIsAppearance = {
    Zero: "0",
    One: "1",
    True: "true",
    False: "false",
} as const;
export type PeopleRelatedRequestIsAppearance =
    (typeof PeopleRelatedRequestIsAppearance)[keyof typeof PeopleRelatedRequestIsAppearance];
