// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

/**
 * Account defaults every key of this account resolves against. Set them with PATCH /v1/me/settings.
 */
export interface AccountSettings {
    transcripts: Arcmira.TranscriptSettings;
}
