// This file was auto-generated by Fern from our API Definition.

export interface Alert {
    /** Alert delivery id. */
    id: string;
    /** Id of the tracker (tracked entity) that produced the alert. */
    tracker_id: string | null;
    /** Id of the monitor the tracker belongs to. Null for trackers outside a monitor. */
    monitor_id: string | null;
    /** Public id ("ent_{n}") of the entity that triggered the alert, when recorded. Null on older rows that were written before entity_id was stored on alert_delivery. Resolve the entity through mention_id or the embedded tracker when this is null. */
    entity_id: string | null;
    /** Public id ("men_{n}") of the mention/appearance row that triggered the alert. Joins directly against mention rows (e.g. /v1/mentions). Null when not appearance-scoped. */
    mention_id: string | null;
    /** YouTube video id (11 characters) of the video that triggered the alert. Null when not media-scoped. */
    video_id: string | null;
    /** Id of the active mention excerpt used as mention evidence. Null when the alert was sent before evidence was recorded. */
    excerpt_id: string | null;
    /** Which evidence layer was sent. Null on older rows. */
    evidence_kind: Alert.EvidenceKind | null;
    /** Delivery channel. Values: email (sent by email), webhook (POSTed to the configured webhook URL), slack (sent to Slack). */
    channel: string;
    /** Delivery status. Values: pending (queued for delivery), sent (delivered), failed (delivery failed; see error_message), skipped (delivery intentionally skipped). */
    status: string;
    /** Terminal status after retries. Null while delivery is still in progress. */
    final_status: string | null;
    /** Error details for failed deliveries. Null unless delivery failed. */
    error_message: string | null;
    /** When delivery was scheduled. Null when delivered immediately. */
    scheduled_at: string | null;
    /** When the alert was actually sent. Null until delivery succeeds. */
    sent_at: string | null;
    /** When the alert row was created. */
    created_at: string;
    /** The tracker the alert belongs to. Fields are null when the tracker row was deleted. */
    tracker: Alert.Tracker;
    /** The monitor the tracker belongs to. Null for trackers outside a monitor. */
    monitor: Alert.Monitor | null;
}

export namespace Alert {
    /** Which evidence layer was sent. Null on older rows. */
    export const EvidenceKind = {
        Excerpt: "excerpt",
    } as const;
    export type EvidenceKind = (typeof EvidenceKind)[keyof typeof EvidenceKind];

    /**
     * The tracker the alert belongs to. Fields are null when the tracker row was deleted.
     */
    export interface Tracker {
        /** Tracker id. */
        id: string | null;
        /** Tracked entity name. */
        entity_name: string | null;
        /** Tracked entity type. */
        entity_type: string | null;
        /** User-facing display name for the tracker. Null when not customized. */
        display_name: string | null;
    }

    /**
     * The monitor the tracker belongs to. Null for trackers outside a monitor.
     */
    export interface Monitor {
        /** Monitor id. */
        id: string;
        /** Monitor name. */
        name: string | null;
    }
}
