// This file was auto-generated by Fern from our API Definition.

/**
 * For issue_type bad_ranking: the expected and observed positions of the row.
 */
export interface BadRankingChange {
    /** Where the row should have ranked (1-based). */
    expected_rank?: number | undefined;
    /** Where the row actually ranked (1-based). Most useful on search feedback. */
    observed_rank?: number | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
