// This file was auto-generated by Fern from our API Definition.

export interface CaptionTrack {
    /** Caption track code, e.g. en or de. Pass it as language to select this track. */
    code: string;
    /** Track name as YouTube reports it. */
    name: string;
    /** True for YouTube automatic captions, false for a track the channel wrote or approved. */
    generated: boolean;
}
