// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface ChannelSponsor {
    entity: Arcmira.EntityRef;
    /** Number of ad_read recommendation rows for this sponsor on the channel. */
    ad_reads: number;
    /** Number of distinct videos containing those ad reads. */
    videos: number;
    /** Publish timestamp of the earliest video with an ad read. Null when unknown. */
    first_seen: string | null;
    /** Publish timestamp of the most recent video with an ad read. Null when unknown. */
    last_seen: string | null;
    /** Curated known-advertiser record for this sponsor/channel pair. Null unless the pair exists in the curated dataset. */
    sponsor_status: ChannelSponsor.SponsorStatus | null;
}

export namespace ChannelSponsor {
    /**
     * Curated known-advertiser record for this sponsor/channel pair. Null unless the pair exists in the curated dataset.
     */
    export interface SponsorStatus {
        /** Curated sponsorship status from the known-advertisers dataset. Values: active (currently sponsoring), lapsed (no recent ad reads), ended (relationship known to have ended), uncertain (signal too weak to classify). */
        status: string;
        /** Curated ad count from the known-advertisers dataset. */
        ad_count: number | null;
        /** Curated first-ad date. Null when not recorded. */
        first_ad_date: string | null;
        /** Curated last-ad date. Null when not recorded. */
        last_ad_date: string | null;
    }
}
