// This file was auto-generated by Fern from our API Definition.

export interface CorrectionSeqMismatchResponse {
    /** Always "Out-of-order correction.". */
    error: string;
    /** The seq the server expects next for this video. Rebase local counters onto it and resend. */
    expectedSeq: number;
}
