// This file was auto-generated by Fern from our API Definition.

export interface CorrectionAcceptedResponse {
    /** Always true on acceptance. */
    ok: boolean;
    /** The correction kind, echoed back. */
    kind: CorrectionAcceptedResponse.Kind;
    /** The stored pending-review row (kind-specific fields). Always carries the row id: use it with the matching withdrawal DELETE. */
    result: Record<string, unknown>;
}

export namespace CorrectionAcceptedResponse {
    /** The correction kind, echoed back. */
    export const Kind = {
        LineEdit: "line_edit",
        SpeakerReassign: "speaker_reassign",
        SpeakerIdentify: "speaker_identify",
        AddPerson: "add_person",
        EntityTag: "entity_tag",
        SegmentRewrite: "segment_rewrite",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
