// This file was auto-generated by Fern from our API Definition.

/**
 * For issue_type delivery_issue: targets the alert delivery (the correction id) and names the channel that was wrong or never received.
 */
export interface DeliveryIssueChange {
    /** The delivery channel the issue concerns. Values: email, webhook, slack. */
    channel: DeliveryIssueChange.Channel;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace DeliveryIssueChange {
    /** The delivery channel the issue concerns. Values: email, webhook, slack. */
    export const Channel = {
        Email: "email",
        Webhook: "webhook",
        Slack: "slack",
    } as const;
    export type Channel = (typeof Channel)[keyof typeof Channel];
}
