// This file was auto-generated by Fern from our API Definition.

export interface EntityRef {
    /** Public entity id in the form "ent_{n}". */
    id: string;
    /** Canonical entity name. */
    name: string;
    /** Entity type. Values: person (an individual), organization (a company or institution; legacy entities may read company or brand), product (a product or service), topic (a subject or theme), channel (a media source such as a YouTube channel), unknown (type was never classified). */
    type: string;
    /** URL slug, the site's canonical id for every type but channel. Null when never slugged. */
    slug: string | null;
    /** The entity's page on arcmira.com, absolute. Link the name to it when you write the entity into an answer. Null for a type the site has no page for. */
    page: string | null;
}
