// This file was auto-generated by Fern from our API Definition.

/**
 * Commercial-intelligence rollup. Only present for organization and product entities when the caller has Recommendations API access (a Pro+ plan) and a brand profile exists.
 */
export interface EntityDetailRecommendationsSummary {
    /** Total ad_read recommendations across all channels. 0 when none. */
    total_ad_reads: number;
    /** Total endorsement recommendations across all channels. 0 when none. */
    total_endorsements: number;
    /** Number of distinct shows/channels with commercial mentions of this entity. */
    unique_shows: number;
    /** Timestamp of the earliest commercial mention. Null until the brand profile has been computed. */
    first_seen_at: string | null;
    /** Timestamp of the most recent commercial mention. Null until the brand profile has been computed. */
    last_seen_at: string | null;
    /** Number of channels where this entity appears in the curated known-advertisers dataset. */
    channels_as_sponsor: number;
}
