// This file was auto-generated by Fern from our API Definition.

export interface Entity {
    /** Public entity id in the form "ent_{n}". Always the canonical entity id. */
    id: string;
    /** Public id of the canonical entity. Identical to id. */
    canonical_id: string;
    /** Canonical entity name. */
    name: string;
    /** Entity type. Values: person (an individual), organization (a company or institution; legacy rows may read company or brand), product (a product or service), topic (a subject or theme), channel (a media source such as a YouTube channel), unknown (type was never classified). */
    type: string;
    /** Source platform for channel entities, e.g. "youtube". Null unless the entity is platform-bound. */
    platform: string | null;
    /** Canonical external URL for the entity. Null when none is known. */
    url: string | null;
    /** Entity image URL. Null until an image has been resolved. */
    image_url: string | null;
    /** Timestamp of the last image resolution attempt. Null until the image pipeline has visited this entity. */
    image_checked_at: string | null;
    /** Number of indexed appearance/mention rows for this entity. 0 when never counted. */
    appearance_count?: number | undefined;
    /** Public id ("ent_{n}") of the owning entity, e.g. the organization behind a product. Null unless an ownership link exists. */
    owner_entity_id: string | null;
    /** True when the id you supplied is the canonical entity. False when your id was merged into this canonical record. */
    is_canonical: boolean;
    /** Public id you supplied when it differs from the canonical entity, i.e. your id was merged into this record. Null unless a merge redirect happened. */
    merged_from_id: string | null;
    /** URL slug, the site's canonical id for every type but channel. Null when never slugged. */
    slug: string | null;
    /** Site-relative route of this entity's page on arcmira.com, e.g. "/org/ramp", "/person/jane-doe", "/yt/@TBPNLive". Null for a type the site has no page for. */
    route: string | null;
    /** The entity's page on arcmira.com, absolute. Link the name to it when you write the entity into an answer. Null for a type the site has no page for. */
    page: string | null;
    /** For a person, the list of their appearances on arcmira.com (their page opens on it). Null for every other type. */
    appearances_page: string | null;
    /** For a person, the list of mentions of them on arcmira.com, page/mentions. Null for every other type: their page is the mentions list already. */
    mentions_page: string | null;
}
