// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface EntityResolveResponse {
    /** The q parameter echoed back. */
    query: string;
    /** The context parameter echoed back. */
    context: string | null;
    /** exact: one entity is named q (or the handle, id or alias), and no better-known person carries the name. single_fuzzy: the only entity returned, not an exact name. ambiguous: several exact matches, or an exact match next to a better-known person sharing the name (Jordan the brand vs Michael Jordan). fuzzy: only loose matches. none: no match. */
    confidence: EntityResolveResponse.Confidence;
    best: Arcmira.ResolveCandidate | null;
    suggested: Arcmira.ResolveSuggestion | null;
    /** Set when best and suggested are both null and several entities fit: show the options to the user, or check every option id against the data and answer per entity. */
    ask: EntityResolveResponse.Ask | null;
    /** Entities considered: exact names first, then initials, whole-word, spelling and substring matches, each by appearance count. */
    candidates: (Arcmira.ResolveCandidate | null)[];
    /** One steering sentence for the agent reading this. */
    note: string;
}

export namespace EntityResolveResponse {
    /** exact: one entity is named q (or the handle, id or alias), and no better-known person carries the name. single_fuzzy: the only entity returned, not an exact name. ambiguous: several exact matches, or an exact match next to a better-known person sharing the name (Jordan the brand vs Michael Jordan). fuzzy: only loose matches. none: no match. */
    export const Confidence = {
        Exact: "exact",
        SingleFuzzy: "single_fuzzy",
        Ambiguous: "ambiguous",
        Fuzzy: "fuzzy",
        None: "none",
    } as const;
    export type Confidence = (typeof Confidence)[keyof typeof Confidence];

    /**
     * Set when best and suggested are both null and several entities fit: show the options to the user, or check every option id against the data and answer per entity.
     */
    export interface Ask {
        question: string;
        options: Ask.Options.Item[];
    }

    export namespace Ask {
        export type Options = Options.Item[];

        export namespace Options {
            export interface Item {
                id: string;
                name: string;
                type: string;
                /** One line to show the user: name, type, description, appearance count. */
                label: string;
            }
        }
    }
}
