// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface EntityChannelListResponse {
    /** Channels whose media carry the entity, highest count first by default. */
    items: EntityChannelListResponse.Items.Item[];
    /** Rows matching the filter across all pages. */
    total: number;
    /** Page size applied, after the plan clamp. */
    limit: number;
    /** True when more rows exist past this page. */
    has_more: boolean;
    /** Opaque cursor for the next page. Null on the last page. */
    next_cursor: string | null;
    /** Which orderings and filters this list can serve right now. A list served from a stored top-N serves only the highest counts. */
    exportCapabilities: EntityChannelListResponse.ExportCapabilities;
    _meta: Arcmira.ExposureMeta;
}

export namespace EntityChannelListResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            /** Raw integer entity id of the channel. */
            id: number;
            /** Channel name. */
            name: string;
            /** Distinct media on this channel counted for the entity: appearances for a person, mentions otherwise. Null when the plan hides counts. */
            count: number | null;
            /** Channel avatar URL. Null until an image has been resolved. */
            imageUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            imageCheckedAt: string | null;
        }
    }

    /**
     * Which orderings and filters this list can serve right now. A list served from a stored top-N serves only the highest counts.
     */
    export interface ExportCapabilities {
        /** Always true: the highest-count ordering is always available. */
        highestCount: boolean;
        /** True when the lowest-count ordering is available. */
        lowestCount: boolean;
        /** True when sort keys other than count are available. */
        alternateSort: boolean;
        /** True when the q filter is available. */
        search: boolean;
        /** Present only when a stored top-N is smaller than the full result set: the rows it holds. */
        availableRows?: number | undefined;
    }
}
