// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface EntityPageMention {
    /** Raw appearance row id (the first row for the video), as a string. */
    id: string;
    /** Publish date as locale display text, or Unknown. */
    date: string;
    /** Publish timestamp. Null when unknown. */
    publishedAt: string | null;
    /** Video title. */
    title: string | null;
    /** Source channel name, or Unknown Channel. */
    channel: string;
    /** YouTube channel id of the source channel. Null when unknown. */
    channelId: string | null;
    /** YouTube handle of the source channel. Null when unknown. */
    channelHandle: string | null;
    /** Always youtube. */
    platform: EntityPageMention.Platform;
    /** Video thumbnail URL. */
    thumbnail: string;
    /** Video thumbnail URL. Same value as thumbnail. */
    thumbnailUrl: string;
    /** YouTube video id (11 characters). */
    videoId: string;
    /** Video length in seconds. Null when unknown. */
    duration: number | null;
    /** Always mention. */
    type: EntityPageMention.Type;
    /** Description of the mention, or "No description available". */
    context: string;
    /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). Absent when no mention in the video carries a score. */
    sentiment?: EntityPageMention.Sentiment | undefined;
    /** Earliest mention timestamp as MM:SS text. Null when the mention covers the full episode. */
    timestamp: string | null;
    /** Earliest mention timestamp as stored. Null when none. */
    rawTimestamp: string | null;
    /** Mentions of the entity in this video. At least 1. */
    mentionCount: number;
    /** Every non-zero mention timestamp in the video, as MM:SS text. Absent when there are none. */
    allTimestamps?: string[] | undefined;
    quote?: Arcmira.PublishedQuote | undefined;
    /** A speakerless excerpt naming the entity, present only when no quote exists for this media. */
    excerpt?: EntityPageMention.Excerpt | undefined;
}

export namespace EntityPageMention {
    /** Always youtube. */
    export const Platform = {
        Youtube: "youtube",
    } as const;
    export type Platform = (typeof Platform)[keyof typeof Platform];
    /** Always mention. */
    export const Type = {
        Mention: "mention",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). Absent when no mention in the video carries a score. */
    export const Sentiment = {
        Positive: "positive",
        Neutral: "neutral",
        Negative: "negative",
    } as const;
    export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];

    /**
     * A speakerless excerpt naming the entity, present only when no quote exists for this media.
     */
    export interface Excerpt {
        /** Published excerpt id. */
        id: string;
        /** The transcript span that names the entity. */
        exactText: string;
        /** Transcript text immediately before the span. */
        contextBefore?: string | undefined;
        /** Transcript text immediately after the span. */
        contextAfter?: string | undefined;
        /** The surface form that matched in the transcript, which may be an approved alias. */
        term: string;
        /** Character offset where term starts. */
        termCharStart: number;
        /** Character offset where term ends. */
        termCharEnd: number;
        /** Span start in the video, in seconds. */
        startSeconds: number;
        /** Span end in the video, in seconds. */
        endSeconds?: number | undefined;
        /** Transcript source class of the excerpt. */
        publicSourceClass: Excerpt.PublicSourceClass;
    }

    export namespace Excerpt {
        /** Transcript source class of the excerpt. */
        export const PublicSourceClass = {
            ArcmiraPremiumExcerpt: "arcmira_premium_excerpt",
            CreatorCaptions: "creator_captions",
            ThirdPartyQuick: "third_party_quick",
        } as const;
        export type PublicSourceClass = (typeof PublicSourceClass)[keyof typeof PublicSourceClass];
    }
}
