// This file was auto-generated by Fern from our API Definition.

/**
 * Usage, plan limits, and the access block for this response: what the caller's plan served and what it withheld.
 */
export interface ExposureMeta {
    /** Plan tier of the caller. Values: anonymous, free, hobby, pro, pro_plus, ultra, teams, enterprise. */
    tier: string;
    /** True when the request carried a valid credential. */
    isAuthenticated: boolean;
    /** Rows consumed this period, or lifetime rows on the free tier. */
    rowsUsed: number;
    /** Rows left this period, or lifetime rows left on the free tier. */
    rowsRemaining: number;
    /** Rows included per period, or the lifetime allocation on the free tier. */
    monthlyRows: number;
    /** True when rowsUsed has reached monthlyRows. */
    isOverLimit: boolean;
    /** True when on-demand usage past the included rows is enabled. */
    onDemandEnabled: boolean;
    /** On-demand spend limit in US cents. 0 means unlimited. */
    spendLimitCents: number;
    /** On-demand spend so far this period, in US cents. */
    currentSpendCents: number;
    /** True when the caller can keep reading data right now. */
    canContinue: boolean;
    /** True when the plan serves full data. False when the response is a preview: counts are null and lists are cut. */
    showingFullData: boolean;
    /** lifetime on the free tier, whose rows never reset. monthly on paid tiers. */
    usageLimitType: ExposureMeta.UsageLimitType;
    /** Free tier only: lifetime rows used. Absent on paid tiers. */
    lifetimeRowsUsed?: number | undefined;
    /** Free tier only: lifetime rows allocated. Absent on paid tiers. */
    lifetimeRowsAllocated?: number | undefined;
    /** Present only when the caller is over the limit and cannot continue. Names the fix: upgrade_to_pro, upgrade_or_enable_ondemand, upgrade_or_increase_limit, enable_ondemand, increase_limit, or contact_sales. */
    limitAction?: ExposureMeta.LimitAction | undefined;
    /** Human sentence for the limit banner. Present only alongside limitAction. */
    limitMessage?: string | undefined;
    /** Site path for the limit banner button. Present only alongside limitAction. */
    limitCtaHref?: string | undefined;
    /** The next tier that lifts the limit. Present only alongside limitAction when an upgrade exists. Values: anonymous, free, hobby, pro, pro_plus, ultra, teams, enterprise. */
    limitUpgradeTier?: string | undefined;
    /** Display name of limitUpgradeTier. */
    limitUpgradeTierName?: string | undefined;
    /** The month in credits (1 credit is $0.001; a row is 4 credits). Present only when the credits ledger decides access. */
    credits?: ExposureMeta.Credits | undefined;
    /** True totals behind the returned rows. Each response sets only the keys for its own sections. */
    totals: ExposureMeta.Totals;
    /** Anonymous row limits and the plan's feature flags. */
    limits: ExposureMeta.Limits;
    /** On-demand price per row in US cents, e.g. 0.4. 0 on tiers without on-demand. */
    costPerRowCents: number;
    /** True when this request billed rows past the included allowance. */
    isOverage: boolean;
    /** The anonymous row limits again, under their older key. */
    freeLimit: ExposureMeta.FreeLimit;
    /** Present when the plan withholds the newest media: how much is hidden and a few safe teaser rows. */
    recentPreview?: ExposureMeta.RecentPreview | undefined;
    /** Person pages only: the same band for the mentions list. */
    recentPreviewMentions?: ExposureMeta.RecentPreviewMentions | undefined;
    /** Structured access block: what the plan served and what it withheld. */
    access: ExposureMeta.Access;
    /** Delivery class code the freshness filter ran at. Present only when the plan delays media and the response went through that filter. */
    _dc?: number | undefined;
}

export namespace ExposureMeta {
    /** lifetime on the free tier, whose rows never reset. monthly on paid tiers. */
    export const UsageLimitType = {
        Lifetime: "lifetime",
        Monthly: "monthly",
    } as const;
    export type UsageLimitType = (typeof UsageLimitType)[keyof typeof UsageLimitType];
    /** Present only when the caller is over the limit and cannot continue. Names the fix: upgrade_to_pro, upgrade_or_enable_ondemand, upgrade_or_increase_limit, enable_ondemand, increase_limit, or contact_sales. */
    export const LimitAction = {
        UpgradeToPro: "upgrade_to_pro",
        UpgradeOrEnableOndemand: "upgrade_or_enable_ondemand",
        UpgradeOrIncreaseLimit: "upgrade_or_increase_limit",
        EnableOndemand: "enable_ondemand",
        IncreaseLimit: "increase_limit",
        ContactSales: "contact_sales",
    } as const;
    export type LimitAction = (typeof LimitAction)[keyof typeof LimitAction];

    /**
     * The month in credits (1 credit is $0.001; a row is 4 credits). Present only when the credits ledger decides access.
     */
    export interface Credits {
        /** Credits spendable now: plan, granted, purchased, and on-demand up to its cap. Null when nothing limits it. */
        available: number | null;
        plan: Credits.Plan;
        /** Credits left in granted lots that have not expired. */
        granted: number;
        /** Credits left in purchased top-ups. */
        purchased: number;
        on_demand: Credits.OnDemand;
    }

    export namespace Credits {
        export interface Plan {
            /** Plan credits this month. Null when the plan has no limit. */
            credits: number | null;
            /** Plan credits spent this month. */
            used: number;
            /** YYYY-MM-DD, the first day of next month (UTC), when plan credits reset. */
            resets_at: string;
        }

        export interface OnDemand {
            /** True when on-demand credits are on. */
            enabled: boolean;
            /** The on-demand cap in credits, at $0.002 a credit. Null when uncapped or off. */
            cap_credits: number | null;
            /** On-demand credits spent this month. */
            used: number;
        }
    }

    /**
     * True totals behind the returned rows. Each response sets only the keys for its own sections.
     */
    export interface Totals {
        /** Total media rows: appearances for a person, mentions for other types, episodes for a channel. */
        appearances?: number | undefined;
        /** Person pages only: total media that mention the person. */
        mentions?: number | undefined;
        /** Total related topics. */
        topics?: number | undefined;
        /** Total related people. */
        people?: number | undefined;
        /** Total related organizations, under the legacy key brands. */
        brands?: number | undefined;
        /** Total related products. */
        products?: number | undefined;
        /** Total related channels. */
        channels?: number | undefined;
        /** Total related organizations (organizations list). */
        organizations?: number | undefined;
        /** Channel only: total unique guests. */
        guests?: number | undefined;
        /** Channel only: total hosts. */
        hosts?: number | undefined;
    }

    /**
     * Anonymous row limits and the plan's feature flags.
     */
    export interface Limits {
        /** Media rows an anonymous caller is served. */
        freeAppearances: number;
        /** Sidebar rows per entity type an anonymous caller is served. */
        freeEntitiesPerType: number;
        /** True when the plan includes webhook delivery. */
        webhooksEnabled: boolean;
        /** True when the plan includes export. */
        exportEnabled: boolean;
        /** True when the plan includes API access. */
        apiEnabled: boolean;
    }

    /**
     * The anonymous row limits again, under their older key.
     */
    export interface FreeLimit {
        /** Same as limits.freeAppearances. */
        appearances: number;
        /** Same as limits.freeEntitiesPerType. */
        entities: number;
    }

    /**
     * Present when the plan withholds the newest media: how much is hidden and a few safe teaser rows.
     */
    export interface RecentPreview {
        /** Days of newest media the plan withholds. */
        windowDays: number;
        /** Media rows inside the withheld window. */
        hiddenRecentCount: number;
        /** Rows a free account would unlock. Present only for anonymous callers (freshness code 2). */
        freeAccountUnlockCount?: number | undefined;
        /** Newest publish date inside the withheld window. Absent when nothing is withheld. */
        newestHiddenAt?: string | undefined;
        /** Up to three of the newest withheld rows, with safe fields only. */
        teaserItems?: RecentPreview.TeaserItems.Item[] | undefined;
        /** Which list the withheld rows belong to. */
        subject: RecentPreview.Subject;
        /** The copy experiment this band feeds. Always recent-intel-gate-copy-v1. */
        experiment: RecentPreview.Experiment;
    }

    export namespace RecentPreview {
        export type TeaserItems = TeaserItems.Item[];

        export namespace TeaserItems {
            export interface Item {
                /** Video thumbnail URL. */
                thumbnailUrl: string;
                /** Source channel name. */
                channelName: string;
                /** Publish date of the withheld video. */
                publishedAt: string;
                /** Video length as display text. Null when unknown. */
                duration: string | null;
                /** Video title, truncated server side. */
                title: string;
            }
        }

        /** Which list the withheld rows belong to. */
        export const Subject = {
            Appearances: "appearances",
            Mentions: "mentions",
            Items: "items",
        } as const;
        export type Subject = (typeof Subject)[keyof typeof Subject];
        /** The copy experiment this band feeds. Always recent-intel-gate-copy-v1. */
        export const Experiment = {
            RecentIntelGateCopyV1: "recent-intel-gate-copy-v1",
        } as const;
        export type Experiment = (typeof Experiment)[keyof typeof Experiment];
    }

    /**
     * Person pages only: the same band for the mentions list.
     */
    export interface RecentPreviewMentions {
        /** Days of newest media the plan withholds. */
        windowDays: number;
        /** Media rows inside the withheld window. */
        hiddenRecentCount: number;
        /** Rows a free account would unlock. Present only for anonymous callers (freshness code 2). */
        freeAccountUnlockCount?: number | undefined;
        /** Newest publish date inside the withheld window. Absent when nothing is withheld. */
        newestHiddenAt?: string | undefined;
        /** Up to three of the newest withheld rows, with safe fields only. */
        teaserItems?: RecentPreviewMentions.TeaserItems.Item[] | undefined;
        /** Which list the withheld rows belong to. */
        subject: RecentPreviewMentions.Subject;
        /** The copy experiment this band feeds. Always recent-intel-gate-copy-v1. */
        experiment: RecentPreviewMentions.Experiment;
    }

    export namespace RecentPreviewMentions {
        export type TeaserItems = TeaserItems.Item[];

        export namespace TeaserItems {
            export interface Item {
                /** Video thumbnail URL. */
                thumbnailUrl: string;
                /** Source channel name. */
                channelName: string;
                /** Publish date of the withheld video. */
                publishedAt: string;
                /** Video length as display text. Null when unknown. */
                duration: string | null;
                /** Video title, truncated server side. */
                title: string;
            }
        }

        /** Which list the withheld rows belong to. */
        export const Subject = {
            Appearances: "appearances",
            Mentions: "mentions",
            Items: "items",
        } as const;
        export type Subject = (typeof Subject)[keyof typeof Subject];
        /** The copy experiment this band feeds. Always recent-intel-gate-copy-v1. */
        export const Experiment = {
            RecentIntelGateCopyV1: "recent-intel-gate-copy-v1",
        } as const;
        export type Experiment = (typeof Experiment)[keyof typeof Experiment];
    }

    /**
     * Structured access block: what the plan served and what it withheld.
     */
    export interface Access {
        /** Access block version. Always 1. */
        v: number;
        /** full when the plan serves everything; preview when something was cut. */
        view: Access.View;
        /** Freshness class of the response. live serves the newest media; the others delay it. */
        cls: Access.Cls;
        /** Where the caller stands on the gate ladder. */
        ladder: Access.Ladder;
        /** Rows served, visible, and blurred per section. */
        rows: Access.Rows;
        /** The freshness gate applied. */
        freshness: Access.Freshness;
        /** The timeline the plan serves. */
        chart: Access.Chart;
        /** True when the plan may page past the first page. */
        pagination: boolean;
        /** True when the plan serves counts. When false, row counts are null. */
        showCounts: boolean;
        /** Every resource the plan withheld from this response. Empty when view is full. */
        withheld: Access.Withheld.Item[];
        /** How to lift the gate. Null when view is full. */
        unlock: Access.Unlock | null;
    }

    export namespace Access {
        /** full when the plan serves everything; preview when something was cut. */
        export const View = {
            Full: "full",
            Preview: "preview",
        } as const;
        export type View = (typeof View)[keyof typeof View];
        /** Freshness class of the response. live serves the newest media; the others delay it. */
        export const Cls = {
            Live: "live",
            Warm: "warm",
            Public: "public",
            Cold: "cold",
        } as const;
        export type Cls = (typeof Cls)[keyof typeof Cls];
        /** Where the caller stands on the gate ladder. */
        export const Ladder = {
            Anonymous: "anonymous",
            Free: "free",
            UsageLimit: "usage_limit",
            Unlocked: "unlocked",
        } as const;
        export type Ladder = (typeof Ladder)[keyof typeof Ladder];

        /**
         * Rows served, visible, and blurred per section.
         */
        export interface Rows {
            /** Media rows. */
            media: Rows.Media;
            /** Topic sidebar rows. */
            topics: Rows.Topics;
            /** People, organization, product, and channel sidebar rows. */
            entities: Rows.Entities;
        }

        export namespace Rows {
            /**
             * Media rows.
             */
            export interface Media {
                /** Rows the backend returns for this section. */
                served: number;
                /** Rows the site paints unobscured. */
                visible: number;
                /** Blurred rows the site paints after the visible ones. */
                placeholders: number;
            }

            /**
             * Topic sidebar rows.
             */
            export interface Topics {
                /** Rows the backend returns for this section. */
                served: number;
                /** Rows the site paints unobscured. */
                visible: number;
                /** Blurred rows the site paints after the visible ones. */
                placeholders: number;
            }

            /**
             * People, organization, product, and channel sidebar rows.
             */
            export interface Entities {
                /** Rows the backend returns for this section. */
                served: number;
                /** Rows the site paints unobscured. */
                visible: number;
                /** Blurred rows the site paints after the visible ones. */
                placeholders: number;
            }
        }

        /**
         * The freshness gate applied.
         */
        export interface Freshness {
            /** Delivery class code: 0 live, 1 to 3 delayed classes. */
            code: number;
            /** Days of newest media withheld. 0 when live. */
            delayDays: number;
        }

        /**
         * The timeline the plan serves.
         */
        export interface Chart {
            /** Months of timeline the plan serves. */
            months: number;
        }

        export type Withheld = Withheld.Item[];

        export namespace Withheld {
            export interface Item {
                /** What was withheld. Values: media_rows (media rows past a position), fresh_media (the newest media), sidebar_rows (sidebar rows past a position), counts (row counts), chart (the timeline), pagination (pages past the first). */
                kind: Item.Kind;
                /** Repeats kind, for readers written against the older key. */
                what: Item.What;
                /** media_rows and sidebar_rows only: rows past this position are withheld. */
                beyondRow?: number | undefined;
                /** fresh_media only: days of newest media withheld. */
                windowDays?: number | undefined;
                /** fresh_media only: the publish date cutoff. Null when none applies. */
                cutoff?: (string | null) | undefined;
                /** sidebar_rows only: which sidebar section. */
                section?: Item.Section | undefined;
                /** pagination only: the paging parameter that was refused. Null when none was sent. */
                param?: (Item.Param | null) | undefined;
            }

            export namespace Item {
                /** What was withheld. Values: media_rows (media rows past a position), fresh_media (the newest media), sidebar_rows (sidebar rows past a position), counts (row counts), chart (the timeline), pagination (pages past the first). */
                export const Kind = {
                    MediaRows: "media_rows",
                    FreshMedia: "fresh_media",
                    SidebarRows: "sidebar_rows",
                    Counts: "counts",
                    Chart: "chart",
                    Pagination: "pagination",
                } as const;
                export type Kind = (typeof Kind)[keyof typeof Kind];
                /** Repeats kind, for readers written against the older key. */
                export const What = {
                    MediaRows: "media_rows",
                    FreshMedia: "fresh_media",
                    SidebarRows: "sidebar_rows",
                    Counts: "counts",
                    Chart: "chart",
                    Pagination: "pagination",
                } as const;
                export type What = (typeof What)[keyof typeof What];
                /** sidebar_rows only: which sidebar section. */
                export const Section = {
                    Topics: "topics",
                    Entities: "entities",
                } as const;
                export type Section = (typeof Section)[keyof typeof Section];
                /** pagination only: the paging parameter that was refused. Null when none was sent. */
                export const Param = {
                    Offset: "offset",
                    Cursor: "cursor",
                } as const;
                export type Param = (typeof Param)[keyof typeof Param];
            }
        }

        /**
         * How to lift the gate. Null when view is full.
         */
        export interface Unlock {
            /** The tier that removes the gate. Values: anonymous, free, hobby, pro, pro_plus, ultra, teams, enterprise. */
            tier: string;
            /** Absolute upgrade or sign-up URL carrying its ?src= attribution. */
            url: string;
            /** The surface the unlock link attributes to. */
            src: Unlock.Src;
            /** The limit fix when the caller is over its limit. Null otherwise. */
            limitAction: Unlock.LimitAction | null;
        }

        export namespace Unlock {
            /** The surface the unlock link attributes to. */
            export const Src = {
                AccessEnvelope: "access-envelope",
                ApiBoundary: "api-boundary",
                McpTool: "mcp-tool",
            } as const;
            export type Src = (typeof Src)[keyof typeof Src];
            /** The limit fix when the caller is over its limit. Null otherwise. */
            export const LimitAction = {
                UpgradeToPro: "upgrade_to_pro",
                UpgradeOrEnableOndemand: "upgrade_or_enable_ondemand",
                UpgradeOrIncreaseLimit: "upgrade_or_increase_limit",
                EnableOndemand: "enable_ondemand",
                IncreaseLimit: "increase_limit",
                ContactSales: "contact_sales",
            } as const;
            export type LimitAction = (typeof LimitAction)[keyof typeof LimitAction];
        }
    }
}
