// This file was auto-generated by Fern from our API Definition.

export interface FeedbackReadbackCorrection {
    /** The correction target id as submitted (or a generated placeholder when omitted). */
    item_id: string;
    /** Inferred kind of the target. Values include: recommendation, sponsor_entity, entity, entity_merge, mention, appearance, alert, alert_expectation, unknown. */
    item_kind: string;
    /** The issue_type as submitted. Null when the correction carried only a reason or class. */
    issue_type: string | null;
    /** The commercial reason code as submitted. Null unless the correction was a commercial-class dispute. */
    reason: string | null;
    /** The suggested_change object as submitted. Null when none was supplied. */
    suggested_change: Record<string, unknown> | null;
    /** The per-correction notes as submitted. Null when none were supplied. */
    notes: string | null;
    /** Review status in the public vocabulary. Values: pending_review (submitted; a reviewer has not finished with it), needs_information (a reviewer needs more detail from you; add context in a support thread quoting the feedback_id), accepted (the correction was accepted as submitted), accepted_with_changes (accepted, but the reviewer resolved it differently than proposed), rejected (reviewed and declined), withdrawn (withdrawn by the submitter before review), applied (the accepted change is live in the index; accepted does not imply applied), reverted (a previously applied change was rolled back). */
    status: FeedbackReadbackCorrection.Status;
    /** Reviewer-written public note about how the correction was resolved. Null until a reviewer leaves one. */
    resolution_note: string | null;
    /** When the correction was created. */
    created_at: string | null;
}

export namespace FeedbackReadbackCorrection {
    /** Review status in the public vocabulary. Values: pending_review (submitted; a reviewer has not finished with it), needs_information (a reviewer needs more detail from you; add context in a support thread quoting the feedback_id), accepted (the correction was accepted as submitted), accepted_with_changes (accepted, but the reviewer resolved it differently than proposed), rejected (reviewed and declined), withdrawn (withdrawn by the submitter before review), applied (the accepted change is live in the index; accepted does not imply applied), reverted (a previously applied change was rolled back). */
    export const Status = {
        PendingReview: "pending_review",
        NeedsInformation: "needs_information",
        Accepted: "accepted",
        AcceptedWithChanges: "accepted_with_changes",
        Rejected: "rejected",
        Withdrawn: "withdrawn",
        Applied: "applied",
        Reverted: "reverted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
