// This file was auto-generated by Fern from our API Definition.

/**
 * Any other object shape. Accepted and logged verbatim for human review; prefer the typed shapes above when one fits your issue_type.
 */
export type FreeformSuggestedChange = Record<string, unknown>;
