// This file was auto-generated by Fern from our API Definition.

export interface HealthResponse {
    /** Always "ok" when the API is reachable. */
    status: HealthResponse.Status;
    /** API version. */
    version: HealthResponse.Version;
    /** Current server time (ISO 8601). */
    time: string;
}

export namespace HealthResponse {
    /** Always "ok" when the API is reachable. */
    export const Status = {
        Ok: "ok",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** API version. */
    export const Version = {
        V1: "v1",
    } as const;
    export type Version = (typeof Version)[keyof typeof Version];
}
