// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface Mention {
    /** Public mention id in the form "men_{n}". */
    id: string;
    entity: Arcmira.EntityRef;
    media: Mention.Media;
    /** Start position in the video in integer seconds. 0 means "full episode / no specific moment". Null when the analyzer could not place it in time. */
    start_seconds: number | null;
    /** End position in the video in integer seconds. 0 means "full episode / no specific moment". Null when the analyzer could not place it in time. */
    end_seconds: number | null;
    /** True when the person physically appears/speaks in the media (person entities only). Always false for organization, product, topic, and channel entities. Filtering with is_appearance=true on a non-person entity returns a 400 (appearances_person_only). */
    is_appearance: boolean;
    /** One-sentence description of the mention context. Null when not generated. */
    description: string | null;
    /** Analyzer confidence between 0 and 1. Null for legacy mentions analyzed before confidence scoring. */
    confidence: number | null;
    /** Raw sentiment score between -1 and 1. Null when sentiment was not computed for this mention. */
    sentiment_score: number | null;
    /** Derived sentiment label from sentiment_score. Values: positive (score above 0.2), negative (score below -0.2), neutral (score between -0.2 and 0.2 inclusive, or no score computed). */
    sentiment: Mention.Sentiment;
    /** URL referenced in the mention. Null unless one was extracted. */
    referenced_url: string | null;
    /** Platform referenced in the mention, e.g. "twitter". Null unless one was extracted. */
    referenced_platform: string | null;
    /** Verbatim content extracted for the mention. Null unless extraction ran. */
    extracted_content: string | null;
    /** Only present when the request used details=full (requires a Pro+ plan). */
    recommendations?: Mention.Recommendations | undefined;
}

export namespace Mention {
    export interface Media {
        /** YouTube video id (11 characters). */
        video_id: string;
        /** Video title. Null when the video was indexed without metadata. */
        title: string | null;
        /** Video URL. Null when unknown. */
        url: string | null;
        /** Video publish timestamp. Null when unknown. */
        published_at: string | null;
        /** YouTube channel id of the source channel. Null when unknown. */
        channel_id: string | null;
        /** Video view count at index time. Null when never fetched. */
        view_count: number | null;
        /** The channel entity that published the video. Null when the video has not been linked to a channel entity. */
        source_channel: Media.SourceChannel | null;
    }

    export namespace Media {
        /**
         * The channel entity that published the video. Null when the video has not been linked to a channel entity.
         */
        export interface SourceChannel {
            /** Public entity id ("ent_{n}") of the source channel. */
            id: string;
            /** Source channel name. */
            name: string | null;
            /** Source channel URL. Null when unknown. */
            url: string | null;
        }
    }

    /** Derived sentiment label from sentiment_score. Values: positive (score above 0.2), negative (score below -0.2), neutral (score between -0.2 and 0.2 inclusive, or no score computed). */
    export const Sentiment = {
        Positive: "positive",
        Neutral: "neutral",
        Negative: "negative",
    } as const;
    export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];

    /**
     * Only present when the request used details=full (requires a Pro+ plan).
     */
    export interface Recommendations {
        /** Commercial mentions (sponsored and organic) for the same entity in the same video. */
        items: Arcmira.RecommendationEnrichmentItem[];
    }
}
