// This file was auto-generated by Fern from our API Definition.

export interface MentionCountsResponse {
    /** The mode applied. */
    mode: MentionCountsResponse.Mode;
    publishedAfter: string | null;
    publishedBefore: string | null;
    /** The channel ids counted. */
    channelIds: string[];
    /** The video ids the count was scoped to. Empty when it was not. */
    videoIds: string[];
    /** One row per entity and channel, ranked by count. */
    rows: MentionCountsResponse.Rows.Item[];
    returned: number;
    /** True when more entity and channel pairs exist past limit. */
    has_more: boolean;
    /** Entities on two or more of the requested channels, ranked by the smallest per-channel count. Empty for one channel. */
    shared: MentionCountsResponse.Shared.Item[];
    /** Newest media across rows. Null when there are none. */
    as_of: string | null;
    /** One steering sentence for the agent reading this. */
    note: string;
}

export namespace MentionCountsResponse {
    /** The mode applied. */
    export const Mode = {
        Mentions: "mentions",
        Appearances: "appearances",
        Both: "both",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            /** Public entity id ("ent_{n}"). */
            entity_id: string;
            name: string;
            type: string;
            /** The entity's page on arcmira.com, absolute. Link the name to it when you write the entity into an answer. Null for a type the site has no page for. */
            page: string | null;
            /** For a person, the list of their appearances on arcmira.com (their page opens on it). Null for every other type. */
            appearances_page: string | null;
            /** For a person, the list of mentions of them on arcmira.com, page/mentions. Null for every other type: their page is the mentions list already. */
            mentions_page: string | null;
            /** URL slug. Null when never slugged. */
            slug: string | null;
            channel_id: string | null;
            channel_name: string | null;
            /** The channel's page on arcmira.com, absolute. Null when no channel is known. */
            channel_page: string | null;
            /** Episodes the entity came up in. */
            count: number;
            /** Times the entity came up across those episodes (mentions or appearances per mode). */
            occurrences: number;
            /** Newest media in this count. */
            as_of: string | null;
        }
    }

    export type Shared = Shared.Item[];

    export namespace Shared {
        export interface Item {
            entity_id: string;
            name: string;
            type: string;
            /** The entity's page on arcmira.com, absolute. Link the name to it when you write the entity into an answer. Null for a type the site has no page for. */
            page: string | null;
            /** For a person, their appearances list. Null otherwise. */
            appearances_page: string | null;
            /** For a person, the mentions of them. Null otherwise. */
            mentions_page: string | null;
            /** URL slug. Null when never slugged. */
            slug: string | null;
            /** How many of the requested channels carry this entity. */
            channel_count: number;
            by_channel: Item.ByChannel.Item[];
        }

        export namespace Item {
            export type ByChannel = ByChannel.Item[];

            export namespace ByChannel {
                export interface Item {
                    /** YouTube channel id. */
                    channel_id: string | null;
                    channel_name: string | null;
                    /** The channel's page on arcmira.com, absolute. Null when no channel is known. */
                    channel_page: string | null;
                    /** Episodes the entity came up in. */
                    count: number;
                    /** Times the entity came up across those episodes (mentions or appearances per mode). */
                    occurrences: number;
                    /** Newest media in this count. */
                    as_of: string | null;
                }
            }
        }
    }
}
