// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface MeResponse {
    /** Id of the user the API key belongs to. */
    user_id: string | null;
    /** Plan tier, e.g. free, hobby, pro, teams, enterprise. */
    tier: string;
    /** Scopes granted to this API key, e.g. read, monitors:write, trackers:write, recommendations:read. */
    scopes: string[];
    /** Requests allowed per 60-second window for this key: 600 for enterprise/teams, 240 for other paid tiers, 60 for free, unless a per-key override is set. */
    rate_limit: number;
    /** True when the plan includes the Recommendations API (commercial intelligence endpoints). */
    recommendations_api_enabled: boolean;
    usage: MeResponse.Usage;
    settings: Arcmira.AccountSettings;
}

export namespace MeResponse {
    export interface Usage {
        /** Premium rows consumed this period. */
        rows_used: number;
        /** Premium rows left this period. */
        rows_remaining: number;
        /** Total premium rows included per period. */
        monthly_rows: number;
        /** On-demand overage spend so far this period, in US cents. */
        current_spend_cents: number;
    }
}
