// This file was auto-generated by Fern from our API Definition.

/**
 * For issue_type missed_alert: an expectation with no alert row to target. Omit the correction id and describe where the alert should have fired.
 */
export interface MissedAlertChange {
    /** URL of the media that should have produced an alert. */
    source_url: string;
    /** Approximate position of the missed occurrence, in seconds from the start of the media. */
    approximate_timestamp_seconds?: number | undefined;
    /** Public id ("ent_{n}") of the tracked entity the missed alert concerns. */
    entity_id?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
