// This file was auto-generated by Fern from our API Definition.

/**
 * For issue_type missing_result: what should have been returned. Put video/channel/timestamp context in notes.
 */
export interface MissingResultChange {
    /** Name of the missing entity or result. */
    name?: string | undefined;
    /** Type of the missing entity: person, organization, product, topic, or channel. */
    entity_type?: string | undefined;
    /** URL evidencing the missing result (video, channel, or article). */
    source_url?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
