// This file was auto-generated by Fern from our API Definition.

export interface MonitorEntityResult {
    /** The entity id as requested. */
    entity_id: string;
    /** Present when entity_id was merged: the canonical entity the tracker follows. */
    canonical_entity_id?: string | undefined;
    /** The tracker that follows the entity: an existing one when the account already tracked it, else the one this request created. Null when no tracker could be used (see reason). */
    tracker_id: string | null;
    /** true when this request created the tracker. */
    created: boolean;
    /** true when the tracker is in this monitor after the request, including when it already was. */
    attached: boolean;
    /** Why attached is false. Values: entity_not_found (no entity has this id), entity_type_not_trackable (only person, organization, product, topic and channel entities can be tracked), tracker_limit_reached (the plan allows no more trackers; upgrade the plan for more), tracked_in_another_monitor (the account already follows this entity in current_monitor_id; it was left there, so move it with POST /v1/monitors/{id}/trackers if the user wants). */
    reason?: MonitorEntityResult.Reason | undefined;
    /** With reason tracked_in_another_monitor: the monitor the tracker is in. */
    current_monitor_id?: string | undefined;
}

export namespace MonitorEntityResult {
    /** Why attached is false. Values: entity_not_found (no entity has this id), entity_type_not_trackable (only person, organization, product, topic and channel entities can be tracked), tracker_limit_reached (the plan allows no more trackers; upgrade the plan for more), tracked_in_another_monitor (the account already follows this entity in current_monitor_id; it was left there, so move it with POST /v1/monitors/{id}/trackers if the user wants). */
    export const Reason = {
        EntityNotFound: "entity_not_found",
        EntityTypeNotTrackable: "entity_type_not_trackable",
        TrackerLimitReached: "tracker_limit_reached",
        TrackedInAnotherMonitor: "tracked_in_another_monitor",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
