// This file was auto-generated by Fern from our API Definition.

export interface MonitorTrackersResponse {
    /** Trackers in the monitor, newest first. */
    trackers: MonitorTrackersResponse.Trackers.Item[];
    /** Number of trackers returned. */
    count: number;
}

export namespace MonitorTrackersResponse {
    export type Trackers = Trackers.Item[];

    export namespace Trackers {
        export interface Item {
            /** Tracker id. */
            id: string;
            /** Tracked entity name. */
            entity_name: string;
            /** Tracked entity type. */
            entity_type: string;
            /** User-facing display name. Falls back to entity_name when not customized. */
            display_name: string;
            /** True when the tracker is paused. */
            paused: boolean;
            /** When the tracker was paused. Null unless paused. */
            paused_at: string | null;
            /** When the tracker last produced an alert. Null until the first alert. */
            last_notified_at: string | null;
            /** When the tracker was created. */
            created_at: string;
            /** When the tracker was last updated. */
            updated_at: string | null;
            /** The monitor id from the request path. */
            monitor_id: string;
        }
    }
}
