// This file was auto-generated by Fern from our API Definition.

export interface MonitorTrackersResponse {
    /** Trackers in the monitor, newest first. */
    trackers: MonitorTrackersResponse.Trackers.Item[];
    /** Number of trackers returned. */
    count: number;
}

export namespace MonitorTrackersResponse {
    export type Trackers = Trackers.Item[];

    export namespace Trackers {
        export interface Item {
            /** Tracker id. */
            id: string;
            /** Tracked entity name. */
            entityName: string;
            /** Tracked entity type. */
            entityType: string;
            /** User-facing display name. Falls back to entityName when not customized. */
            displayName: string;
            /** True when the tracker is paused. */
            isPaused: boolean;
            /** When the tracker was paused. Null unless paused. */
            pausedAt: string | null;
            /** When the tracker last produced an alert. Null until the first alert. */
            lastNotifiedAt: string | null;
            /** When the tracker was created. */
            createdAt: string;
            /** When the tracker was last updated. */
            updatedAt: string | null;
            /** The monitor id from the request path. */
            monitorId: string;
        }
    }
}
