// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface MonitorListResponse {
    /** All monitors for the account, ordered by dashboard sort position, then name. */
    monitors: MonitorListResponse.Monitors.Item[];
}

export namespace MonitorListResponse {
    export type Monitors = Monitors.Item[];

    export namespace Monitors {
        export interface Item extends Arcmira.Monitor {
            /** Number of trackers in the monitor. */
            trackerCount: number;
            /** Alert deliveries written for this monitor since the start of the calendar month. */
            alertsThisMonth: number;
            /** Display metadata for the connected Slack integration. Null/absent when Slack is not configured. */
            slackIntegration?: (Item.SlackIntegration | null) | undefined;
        }

        export namespace Item {
            /**
             * Display metadata for the connected Slack integration. Null/absent when Slack is not configured.
             */
            export interface SlackIntegration {
                /** Slack integration id. */
                id: string;
                /** Slack workspace name. */
                team_name: string | null;
                /** Slack channel the integration posts to. */
                channel_name: string | null;
            }
        }
    }
}
