// This file was auto-generated by Fern from our API Definition.

export interface MonitorDeleteResponse {
    /** Human-readable confirmation. */
    message: string;
    /** Number of trackers that were deleted along with the monitor. */
    trackers_deleted: number;
}
