// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface MonitorMutationResponse {
    monitor: MonitorMutationResponse.Monitor;
    /** Human-readable confirmation. */
    message: string;
}

export namespace MonitorMutationResponse {
    export interface Monitor extends Arcmira.Monitor {
        /** Number of trackers in the monitor. Always 0 in the create response. */
        trackerCount: number;
        /** The webhook signing secret ("whsec_..."). Only present when this request NEWLY enabled webhook signing: a create with notifyWebhook: true and a webhookUrl, or a PATCH that turns the webhook on (or sets a URL) where no secret existed before. Returned only once. Store it securely; it cannot be retrieved later. To recover from a lost secret, rotate. */
        webhookSecret?: string | undefined;
    }
}
