// This file was auto-generated by Fern from our API Definition.

export interface NamedEntityRef {
    /** Public entity id, ent_{n}. */
    id: string;
    /** The entity name. Null when the id no longer resolves. */
    name: string | null;
    /** Entity type. Values: person (an individual), organization (a company or institution; legacy entities may read company or brand), product (a product or service), topic (a subject or theme), channel (a media source such as a YouTube channel), unknown (type was never classified). */
    type: string | null;
}
