// This file was auto-generated by Fern from our API Definition.

/**
 * This OpenAPI 3.1 document, the one you are reading.
 */
export interface OpenApiDocument {
    /** OpenAPI version, 3.1.0. */
    openapi: string;
    /** API metadata. */
    info: OpenApiDocument.Info;
    /** Base URLs the API is served from. */
    servers: OpenApiDocument.Servers.Item[];
    /** Every operation, keyed by path then HTTP method. An open map: each value is an OpenAPI path item object. */
    paths: Record<string, Record<string, unknown>>;
    /** Shared schemas and security schemes, keyed by component kind then name. An open map of OpenAPI component objects. */
    components: Record<string, Record<string, unknown>>;
}

export namespace OpenApiDocument {
    /**
     * API metadata.
     */
    export interface Info {
        /** API title. */
        title: string;
        /** API version. */
        version: string;
        /** Who publishes the API. */
        contact: Info.Contact;
    }

    export namespace Info {
        /**
         * Who publishes the API.
         */
        export interface Contact {
            /** Contact name. */
            name: string;
            /** Contact URL. */
            url: string;
        }
    }

    export type Servers = Servers.Item[];

    export namespace Servers {
        export interface Item {
            /** Base URL. */
            url: string;
        }
    }
}
