// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface PersonAppearanceListResponse {
    /** Media the person appeared in, newest first by default, one row per video. */
    items: PersonAppearanceListResponse.Items.Item[];
    /** Rows matching the filter across all pages. */
    total: number;
    /** Row offset of this page, as the cursor encoded it. 0 on the first page. */
    offset: number;
    /** Page size applied, after the plan clamp. */
    limit: number;
    /** Same value as has_more, kept for readers of the web shape. */
    hasMore: boolean;
    /** True when more rows exist past this page. */
    has_more: boolean;
    /** Opaque cursor for the next page. Null on the last page. */
    next_cursor: string | null;
    _meta: Arcmira.ExposureMeta;
}

export namespace PersonAppearanceListResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            /** Raw appearance row id (the first row for the video), as a string. */
            id: string;
            /** Publish date as locale display text, or Unknown. */
            date: string;
            /** Publish timestamp. Null when unknown. */
            dateRaw: string | null;
            /** Video title. */
            title: string | null;
            /** Source channel name, or Unknown Channel. */
            channel: string;
            /** YouTube channel id of the source channel. Null when unknown. */
            channelId: string | null;
            /** YouTube handle of the source channel. Null when unknown. */
            channelHandle: string | null;
            /** Always youtube. */
            platform: Item.Platform;
            /** host when the person hosts the channel, guest otherwise. mention only when the request passed is_appearance=false, which lists media that mention the person instead. */
            type: Item.Type;
            /** Longest description of the appearance, or "No description available". */
            context: string;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Video thumbnail URL. */
            thumbnail: string;
            /** YouTube video id (11 characters). */
            videoId: string;
            /** Earliest start timestamp as MM:SS text, or "Full Episode" when none. */
            timestamp: string;
            /** Earliest start timestamp as stored. Null when none. */
            rawTimestamp: string | null;
            /** Video length in seconds. Null when unknown. */
            duration: number | null;
            /** Video view count at index time. Null when never fetched. */
            viewCount: number | null;
            excerpt?: Arcmira.PublishedExcerpt | undefined;
        }

        export namespace Item {
            /** Always youtube. */
            export const Platform = {
                Youtube: "youtube",
            } as const;
            export type Platform = (typeof Platform)[keyof typeof Platform];
            /** host when the person hosts the channel, guest otherwise. mention only when the request passed is_appearance=false, which lists media that mention the person instead. */
            export const Type = {
                Host: "host",
                Guest: "guest",
                Mention: "mention",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }
}
