// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface PersonPageResponse {
    /** The person: the stored entity row plus camelCase image fields and what the person owns. */
    entity: PersonPageResponse.Entity;
    /** A verified CEO role for the person. Null when none is verified. */
    roleEdge: PersonPageResponse.RoleEdge | null;
    /** Headline numbers for the person. */
    stats: PersonPageResponse.Stats;
    /** Appearances per month. Twelve months ending this month, oldest first. Empty when the plan withholds the chart. */
    appearancesByMonth: PersonPageResponse.AppearancesByMonth.Item[];
    /** Media mentioning the person per month. Twelve months ending this month, oldest first. Empty when the plan withholds the chart. */
    mentionsByMonth: PersonPageResponse.MentionsByMonth.Item[];
    /** Topics in the media the person appeared in, highest count first. */
    topics: PersonPageResponse.Topics.Item[];
    /** People in the media the person appeared in, highest count first. */
    people: PersonPageResponse.People.Item[];
    /** Organizations in the media the person appeared in, highest count first. */
    brands: PersonPageResponse.Brands.Item[];
    /** Products in the media the person appeared in, highest count first. */
    products: PersonPageResponse.Products.Item[];
    /** Newest media the person appeared in, one row per video, cut to the plan's media rows. */
    appearances: PersonPageResponse.Appearances.Item[];
    /** Newest media that mention the person without them appearing, one row per video. */
    mentions: PersonPageResponse.Mentions.Item[];
    _meta: Arcmira.ExposureMeta;
}

export namespace PersonPageResponse {
    /**
     * The person: the stored entity row plus camelCase image fields and what the person owns.
     */
    export interface Entity {
        /** Raw integer entity id. */
        id: number;
        /** Person name. */
        name: string;
        /** Stored entity type. Always person. */
        type: string;
        /** Source platform. Null for people. */
        platform: string | null;
        /** External URL for the person. Null when none is known. */
        url: string | null;
        /** When the entity row was created. */
        created_at: string;
        /** Person image URL. Null until resolved. */
        image_url: string | null;
        /** When the image pipeline last checked this entity. Null until checked. */
        image_checked_at: string | null;
        /** Raw id of the entity this one was merged into. Null on a canonical entity, which a page always serves. */
        merged_into_entity_id: number | null;
        /** Raw id of the owning entity. Null unless an ownership link exists. */
        owner_entity_id: number | null;
        /** YouTube channel id. Null for people. */
        youtube_channel_id: string | null;
        /** YouTube handle. Null for people. */
        youtube_handle: string | null;
        /** 1 when the entity is flagged priority, 0 or null otherwise. */
        is_priority: number | null;
        /** Up to 10 channels this entity owns, most videos first. Null when it owns none. */
        ownedChannels: Entity.OwnedChannels.Item[] | null;
        /** Up to 10 products this entity owns, most mentions first. Null when it owns none. */
        ownedProducts: Entity.OwnedProducts.Item[] | null;
    }

    export namespace Entity {
        export type OwnedChannels = OwnedChannels.Item[];

        export namespace OwnedChannels {
            export interface Item {
                /** Raw integer entity id. */
                id: number;
                /** Entity name. */
                name: string;
                /** Label that tells a homonym apart, e.g. "AdQuick (channel)". Equals name when no label is needed. */
                display_name: string;
                /** Entity type: channel or product. */
                type: string;
                /** Site-relative route of the entity page on arcmira.com. */
                route: string;
                /** Entity image URL. Null until resolved. */
                imageUrl: string | null;
                /** When the image pipeline last checked this entity. Null until checked. */
                imageCheckedAt: string | null;
                /** Channels only: media rows published by the channel. */
                videoCount?: number | undefined;
                /** Products only: appearance rows of the product. */
                mentionCount?: number | undefined;
            }
        }

        export type OwnedProducts = OwnedProducts.Item[];

        export namespace OwnedProducts {
            export interface Item {
                /** Raw integer entity id. */
                id: number;
                /** Entity name. */
                name: string;
                /** Label that tells a homonym apart, e.g. "AdQuick (channel)". Equals name when no label is needed. */
                display_name: string;
                /** Entity type: channel or product. */
                type: string;
                /** Site-relative route of the entity page on arcmira.com. */
                route: string;
                /** Entity image URL. Null until resolved. */
                imageUrl: string | null;
                /** When the image pipeline last checked this entity. Null until checked. */
                imageCheckedAt: string | null;
                /** Channels only: media rows published by the channel. */
                videoCount?: number | undefined;
                /** Products only: appearance rows of the product. */
                mentionCount?: number | undefined;
            }
        }
    }

    /**
     * A verified CEO role for the person. Null when none is verified.
     */
    export interface RoleEdge {
        /** Always ceo. */
        role: RoleEdge.Role;
        /** Display label for the role line. */
        label: RoleEdge.Label;
        /** Name of the organization the person leads. */
        name: string;
        /** Site-relative link to the organization page. Null when none. */
        href: string | null;
        /** Display line naming the evidence for the role. Null when there is none to show. */
        receipt: string | null;
        /** Organization logo URL. Null until resolved. */
        imageUrl: string | null;
        /** When the image pipeline last checked the organization. Null until checked. */
        imageCheckedAt: string | null;
    }

    export namespace RoleEdge {
        /** Always ceo. */
        export const Role = {
            Ceo: "ceo",
        } as const;
        export type Role = (typeof Role)[keyof typeof Role];
        /** Display label for the role line. */
        export const Label = {
            CeoOf: "CEO of",
            CoCeoOf: "CO-CEO of",
        } as const;
        export type Label = (typeof Label)[keyof typeof Label];
    }

    /**
     * Headline numbers for the person.
     */
    export interface Stats {
        /** Appearances in the last 90 days. */
        velocity: number;
        /** Reserved. Always 0. */
        sentiment: number;
        /** Total views of the person's appearances as display text, e.g. 1.2M. */
        reach: string;
        /** Total views of the person's appearances. */
        reachRaw: number;
        /** Total appearances. */
        total: number;
        /** Total media that mention the person. */
        totalMentions: number;
        /** Total views of the media that mention the person. */
        totalMentionViews: number;
        /** totalMentionViews as display text. */
        mentionReach: string;
        /** Newest publish date among the counted media. Null when none. The freshness gate does not withhold it. */
        latestMediaAt: string | null;
    }

    export type AppearancesByMonth = AppearancesByMonth.Item[];

    export namespace AppearancesByMonth {
        export interface Item {
            /** Three-letter month name, e.g. Jan. */
            month: string;
            /** The month as YYYY-MM. */
            yearMonth: string;
            /** Media that month. Months inside the withheld window read 0. */
            count: number;
        }
    }

    export type MentionsByMonth = MentionsByMonth.Item[];

    export namespace MentionsByMonth {
        export interface Item {
            /** Three-letter month name, e.g. Jan. */
            month: string;
            /** The month as YYYY-MM. */
            yearMonth: string;
            /** Media that month. Months inside the withheld window read 0. */
            count: number;
        }
    }

    export type Topics = Topics.Item[];

    export namespace Topics {
        export interface Item {
            /** Topic name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }

    export type People = People.Item[];

    export namespace People {
        export interface Item {
            /** Person name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Person image URL. Null until an image has been resolved. */
            imageUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            imageCheckedAt: string | null;
            /** Always Connection. */
            role: Item.Role;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
            /** Always Connection. */
            export const Role = {
                Connection: "Connection",
            } as const;
            export type Role = (typeof Role)[keyof typeof Role];
        }
    }

    export type Brands = Brands.Item[];

    export namespace Brands {
        export interface Item {
            /** Entity name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Logo URL. Null until an image has been resolved. */
            logoUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            logoCheckedAt: string | null;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }

    export type Products = Products.Item[];

    export namespace Products {
        export interface Item {
            /** Entity name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Logo URL. Null until an image has been resolved. */
            logoUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            logoCheckedAt: string | null;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }

    export type Appearances = Appearances.Item[];

    export namespace Appearances {
        export interface Item {
            /** Raw appearance row id (the first row for the video), as a string. */
            id: string;
            /** Publish date as locale display text, or Unknown. */
            date: string;
            /** Publish timestamp. Null when unknown. */
            publishedAt: string | null;
            /** Video title. */
            title: string | null;
            /** Source channel name, or Unknown Channel. */
            channel: string;
            /** YouTube channel id of the source channel. Null when unknown. */
            channelId: string | null;
            /** YouTube handle of the source channel. Null when unknown. */
            channelHandle: string | null;
            /** Always youtube. */
            platform: Item.Platform;
            /** Video thumbnail URL. */
            thumbnail: string;
            /** Video thumbnail URL. Same value as thumbnail. */
            thumbnailUrl: string;
            /** YouTube video id (11 characters). */
            videoId: string;
            /** Video length in seconds. Null when unknown. */
            duration: number | null;
            /** host or guest on an appearance row (host when the person hosts the channel); mention on a mention row. */
            type: Item.Type;
            /** Description of the moment, or "No description available". */
            context: string;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Earliest start timestamp as MM:SS text, or "Full Episode" when none. */
            timestamp: string;
            /** Earliest start timestamp as stored. Null when none. */
            rawTimestamp: string | null;
            quote?: Arcmira.PublishedQuote | undefined;
            excerpt?: Arcmira.PublishedExcerpt | undefined;
        }

        export namespace Item {
            /** Always youtube. */
            export const Platform = {
                Youtube: "youtube",
            } as const;
            export type Platform = (typeof Platform)[keyof typeof Platform];
            /** host or guest on an appearance row (host when the person hosts the channel); mention on a mention row. */
            export const Type = {
                Host: "host",
                Guest: "guest",
                Mention: "mention",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }

    export type Mentions = Mentions.Item[];

    export namespace Mentions {
        export interface Item {
            /** Raw appearance row id (the first row for the video), as a string. */
            id: string;
            /** Publish date as locale display text, or Unknown. */
            date: string;
            /** Publish timestamp. Null when unknown. */
            publishedAt: string | null;
            /** Video title. */
            title: string | null;
            /** Source channel name, or Unknown Channel. */
            channel: string;
            /** YouTube channel id of the source channel. Null when unknown. */
            channelId: string | null;
            /** YouTube handle of the source channel. Null when unknown. */
            channelHandle: string | null;
            /** Always youtube. */
            platform: Item.Platform;
            /** Video thumbnail URL. */
            thumbnail: string;
            /** Video thumbnail URL. Same value as thumbnail. */
            thumbnailUrl: string;
            /** YouTube video id (11 characters). */
            videoId: string;
            /** Video length in seconds. Null when unknown. */
            duration: number | null;
            /** host or guest on an appearance row (host when the person hosts the channel); mention on a mention row. */
            type: Item.Type;
            /** Description of the moment, or "No description available". */
            context: string;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Earliest start timestamp as MM:SS text, or "Full Episode" when none. */
            timestamp: string;
            /** Earliest start timestamp as stored. Null when none. */
            rawTimestamp: string | null;
            quote?: Arcmira.PublishedQuote | undefined;
            excerpt?: Arcmira.PublishedExcerpt | undefined;
        }

        export namespace Item {
            /** Always youtube. */
            export const Platform = {
                Youtube: "youtube",
            } as const;
            export type Platform = (typeof Platform)[keyof typeof Platform];
            /** host or guest on an appearance row (host when the person hosts the channel); mention on a mention row. */
            export const Type = {
                Host: "host",
                Guest: "guest",
                Mention: "mention",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }
}
