// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface PremiumQuote {
    video_id: string;
    duration_seconds: number;
    billing_scope: PremiumQuote.BillingScope;
    owned: boolean;
    eligible: boolean;
    /** Present when eligible is false. Names the plan that includes Premium transcripts, as a button label and an absolute link to its checkout. */
    upgrade?: PremiumQuote.Upgrade | undefined;
    quote: Arcmira.TranscriptQuote;
    charge: PremiumQuote.Charge;
    /** Credits in a row: 4. */
    credits_per_row: number;
    max_on_demand_cents: number;
    /** What one unit of charge.unit costs as on-demand usage, in US cents: 0.2 a credit ($0.002). */
    on_demand_cents_per_unit: number;
    refund_policy: string;
}

export namespace PremiumQuote {
    export const BillingScope = {
        FullVideo: "full_video",
    } as const;
    export type BillingScope = (typeof BillingScope)[keyof typeof BillingScope];

    /**
     * Present when eligible is false. Names the plan that includes Premium transcripts, as a button label and an absolute link to its checkout.
     */
    export interface Upgrade {
        label: string;
        href: string;
    }

    export interface Charge {
        unit: Charge.Unit;
        amount: number;
        /** Where the charge would come from at the current balance. */
        from: Charge.From;
    }

    export namespace Charge {
        export const Unit = {
            Rows: "rows",
            Credits: "credits",
        } as const;
        export type Unit = (typeof Unit)[keyof typeof Unit];
        /** Where the charge would come from at the current balance. */
        export const From = {
            Included: "included",
            OnDemand: "on_demand",
            Mixed: "mixed",
        } as const;
        export type From = (typeof From)[keyof typeof From];
    }
}
