// This file was auto-generated by Fern from our API Definition.

/**
 * The publication window the answer covers, [after, before) in UTC, normalized from after and before.
 */
export interface PublicationWindow {
    /** Inclusive start as an ISO instant. Null when the window has no start. */
    after: string | null;
    /** Exclusive end as an ISO instant. Null when the window has no end. Earlier than the before you sent when your plan's freshness gate cut the window. */
    before: string | null;
}
