// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

/**
 * The refused price, on a priced refusal: quota_exceeded, spend_limit_exceeded and paid_plan_required.
 */
export interface RefusedQuote extends Arcmira.TranscriptQuote {
    /** What the purchase would charge at the current balance. Absent when no current price could be read. */
    charge?: RefusedQuote.Charge | undefined;
    /** The on-demand money, in whole cents, this purchase needs beyond included credits at the current balance. */
    max_on_demand_cents?: number | undefined;
}

export namespace RefusedQuote {
    /**
     * What the purchase would charge at the current balance. Absent when no current price could be read.
     */
    export interface Charge {
        unit: Charge.Unit;
        amount: number;
        /** Where the charge would come from at the current balance. */
        from: Charge.From;
    }

    export namespace Charge {
        export const Unit = {
            Rows: "rows",
            Credits: "credits",
        } as const;
        export type Unit = (typeof Unit)[keyof typeof Unit];
        /** Where the charge would come from at the current balance. */
        export const From = {
            Included: "included",
            OnDemand: "on_demand",
            Mixed: "mixed",
        } as const;
        export type From = (typeof From)[keyof typeof From];
    }
}
