// This file was auto-generated by Fern from our API Definition.

/**
 * Set when best is null but one entity stands out, with the reason and evidence. Use it and tell the user you assumed it.
 */
export interface ResolveSuggestion {
    /** Public entity id in the form "ent_{n}". */
    id: string;
    /** Entity name. */
    name: string;
    /** URL slug. Null when the entity has never been slugged. */
    slug: string | null;
    /** Entity type. Values: person (an individual), organization (a company or institution; legacy entities may read company or brand), product (a product or service), topic (a subject or theme), channel (a media source such as a YouTube channel), unknown (type was never classified). */
    type: string;
    /** Number of indexed appearances and mentions. Results are ordered by this, descending. */
    appearance_count?: number | undefined;
    /** YouTube channel id for channel entities. Null for every other type. */
    youtube_channel_id: string | null;
    /** One catalog sentence that tells entities with the same name apart, for example "Common gender-neutral given name or nickname". Null when the catalog has none. */
    description: string | null;
    /** The entity's page on arcmira.com, absolute. Link the name to it when you write the entity into an answer. Null for a type the site has no page for. */
    page: string | null;
    /** How the entity's name relates to q: the whole name, a run of its words (Michael Jordan for Jordan), characters inside a word, the show's initials (My First Million for MFM), or a near spelling. */
    match: ResolveSuggestion.Match;
    /** Why this entity stands out: dominant (10x the appearances of the next match), only_word_match, context (the context parameter points at it), acronym, spelling. */
    reason: ResolveSuggestion.Reason;
    /** The numbers or words behind the reason, to repeat to the user. */
    evidence: string;
    /** Always true: this is an assumption the answer must state. */
    assumed: boolean;
}

export namespace ResolveSuggestion {
    /** How the entity's name relates to q: the whole name, a run of its words (Michael Jordan for Jordan), characters inside a word, the show's initials (My First Million for MFM), or a near spelling. */
    export const Match = {
        Exact: "exact",
        Word: "word",
        Substring: "substring",
        Acronym: "acronym",
        Spelling: "spelling",
    } as const;
    export type Match = (typeof Match)[keyof typeof Match];
    /** Why this entity stands out: dominant (10x the appearances of the next match), only_word_match, context (the context parameter points at it), acronym, spelling. */
    export const Reason = {
        Dominant: "dominant",
        OnlyWordMatch: "only_word_match",
        Context: "context",
        Acronym: "acronym",
        Spelling: "spelling",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
