// This file was auto-generated by Fern from our API Definition.

export interface SignupVerifiedResponse {
    /** The arc_sk_ account key. Shown once. Send it as Authorization: Bearer. */
    key: string;
    /** The key id. Appears on funnel events and in the dashboard; never a secret. */
    key_id: string;
    /** The pasteable request header line: Authorization: Bearer arc_sk_... */
    header: string;
    /** Always ["read"]. Create an Admin key in the dashboard for account write access. */
    scopes: string[];
    /** The plan the account is on: free for a new account, its plan when the address already had one. */
    tier: string;
    /** The pool this key draws on: a free account's lifetime credits, a paid plan's monthly rows. */
    rows_allotted: number;
    /** A curl command for the first call: GET /v1/me with the key. */
    next: string;
    /** Sign-up documentation. */
    docs_url: string;
}
