// This file was auto-generated by Fern from our API Definition.

export interface SignupVerifiedResponse {
    /** The arc_sk_ account key. Shown once. Send it as Authorization: Bearer. */
    key: string;
    /** The key id. Appears on funnel events and in the dashboard; never a secret. */
    key_id: string;
    /** The pasteable request header line: Authorization: Bearer arc_sk_... */
    header: string;
    /** Always ["read"]. Create an Admin key in the dashboard for account write access. */
    scopes: string[];
    /** The plan the account is on: free for a new account, its plan when the address already had one. */
    tier: string;
    /** Plan credits a month, in rows (a row is 4 credits), on a paid plan. On the free plan, the account's allotment from before credits (1,000 for a new account). The free plan has 1,000 credits a month; read the balance from usage.credits on GET /v1/me. */
    rows_allotted: number;
    /** A curl command for the first call: GET /v1/me with the key. */
    next: string;
    /** Sign-up documentation. */
    docs_url: string;
}
