// This file was auto-generated by Fern from our API Definition.

/**
 * For issue_type stale_metadata: the field and its correct value, with a source URL when you have one.
 */
export interface StaleMetadataChange {
    /** The metadata field that is outdated, e.g. "website" or "name". */
    field?: string | undefined;
    /** The current, correct value. */
    value?: unknown | undefined;
    /** URL evidencing the correct value. */
    source_url?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
