// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TeamSpendResponse {
    /** First day of the current period (YYYY-MM-DD). */
    period_start: string;
    /** Per-member spend rows, earliest join first. */
    data: Arcmira.TeamMemberSpend[];
}
