// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TopicPageResponse {
    /** The topic. */
    entity: TopicPageResponse.Entity;
    /** Headline numbers and section totals for the topic. */
    stats: TopicPageResponse.Stats;
    /** Media mentioning the topic per month. Twelve months ending this month, oldest first. Empty when the plan withholds the chart. */
    mentionsByMonth: TopicPageResponse.MentionsByMonth.Item[];
    /** Co-occurring topics, highest count first. */
    relatedTopics: TopicPageResponse.RelatedTopics.Item[];
    /** People who appeared in media with the topic, highest count first. */
    voices: TopicPageResponse.Voices.Item[];
    /** Co-occurring organizations, highest count first. */
    companies: TopicPageResponse.Companies.Item[];
    /** Co-occurring products, highest count first. */
    products: TopicPageResponse.Products.Item[];
    /** Channels that mention the topic, highest count first. */
    channels: TopicPageResponse.Channels.Item[];
    /** Newest media that mention the entity, one row per video, cut to the plan's media rows. */
    mentions: Arcmira.EntityPageMention[];
    _meta: Arcmira.ExposureMeta;
}

export namespace TopicPageResponse {
    /**
     * The topic.
     */
    export interface Entity {
        /** Raw integer entity id. */
        id: number;
        /** Topic name. */
        name: string;
        /** Always topic. */
        type: Entity.Type;
        /** Topic image URL. Null until resolved. */
        imageUrl: string | null;
        /** When the image pipeline last checked this entity. Null until checked. */
        imageCheckedAt: string | null;
        /** True when the entity is flagged priority. */
        isPriority: boolean;
    }

    export namespace Entity {
        /** Always topic. */
        export const Type = {
            Topic: "topic",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];
    }

    /**
     * Headline numbers and section totals for the topic.
     */
    export interface Stats {
        /** Mentions in the last 7 days. Null when the plan hides it. */
        velocity: number | null;
        /** Mentions in the last 90 days. Null when the plan hides it. */
        velocity90d: number | null;
        /** Reserved. Always 0. */
        sentiment: number;
        /** Total views as display text, e.g. 1.2M. */
        reach: string;
        /** Total views of the media that mention the topic. */
        reachRaw: number;
        /** Total media that mention the topic. */
        total: number;
        /** Newest publish date among the counted media. Null when none. The freshness gate does not withhold it. */
        latestMediaAt: string | null;
        /** Total people who appeared in media with the topic. */
        people: number;
        /** Total co-occurring organizations. */
        organizations: number;
        /** Total co-occurring products. */
        products: number;
        /** Total related topics. */
        topics: number;
        /** Total channels that mention the topic. */
        channels: number;
    }

    export type MentionsByMonth = MentionsByMonth.Item[];

    export namespace MentionsByMonth {
        export interface Item {
            /** Three-letter month name, e.g. Jan. */
            month: string;
            /** The month as YYYY-MM. */
            yearMonth: string;
            /** Media that month. Months inside the withheld window read 0. */
            count: number;
        }
    }

    export type RelatedTopics = RelatedTopics.Item[];

    export namespace RelatedTopics {
        export interface Item {
            /** Topic name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }

    export type Voices = Voices.Item[];

    export namespace Voices {
        export interface Item {
            /** Person name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Person image URL. Null until an image has been resolved. */
            imageUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            imageCheckedAt: string | null;
            /** Always Commentator. */
            role: Item.Role;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
            /** Always Commentator. */
            export const Role = {
                Commentator: "Commentator",
            } as const;
            export type Role = (typeof Role)[keyof typeof Role];
        }
    }

    export type Companies = Companies.Item[];

    export namespace Companies {
        export interface Item {
            /** Entity name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Logo URL. Null until an image has been resolved. */
            logoUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            logoCheckedAt: string | null;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }

    export type Products = Products.Item[];

    export namespace Products {
        export interface Item {
            /** Entity name. */
            name: string;
            /** Media shared with the entity. Null when the plan hides counts (_meta.showingFullData false). */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Logo URL. Null until an image has been resolved. */
            logoUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            logoCheckedAt: string | null;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }

    export type Channels = Channels.Item[];

    export namespace Channels {
        export interface Item {
            /** Channel name. */
            name: string;
            /** Media on this channel that mention the entity. Null when the plan hides counts. */
            count: number | null;
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            sentiment: Item.Sentiment;
            /** Logo URL. Null until an image has been resolved. */
            logoUrl: string | null;
            /** When the image pipeline last checked this entity. Null until checked. */
            logoCheckedAt: string | null;
            /** The channel's page key on arcmira.com: its @handle when known, else its UC id. Null when neither is known. */
            slug: string | null;
        }

        export namespace Item {
            /** Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). */
            export const Sentiment = {
                Positive: "positive",
                Neutral: "neutral",
                Negative: "negative",
            } as const;
            export type Sentiment = (typeof Sentiment)[keyof typeof Sentiment];
        }
    }
}
