// This file was auto-generated by Fern from our API Definition.

export interface Tracker {
    /** Tracker id in the form "trk_{hex}". */
    id: string;
    /** The tracked entity name, as submitted. */
    entityName: string;
    /** The tracked entity type. Values: person, organization, product, topic, channel. */
    entityType: string;
    /** User-facing display name. Falls back to entityName when not customized. */
    displayName: string;
    /** True when this tracker delivers by email (default true at creation). */
    notifyEmail: boolean;
    /** True when this tracker has a per-tracker webhook override enabled. */
    notifyWebhook: boolean;
    /** True when this tracker has a per-tracker Slack override enabled. */
    notifySlack: boolean;
    /** Per-tracker webhook destination override. Null when the tracker uses its monitor's delivery settings. */
    webhookUrl: string | null;
    /** Per-tracker Slack channel override. Null when not set. */
    slackChannelId: string | null;
    /** Per-tracker Slack integration override. Null when not set. */
    slackIntegrationId: string | null;
    /** Optional matching filters as submitted. Null when none were set. */
    filters: Record<string, unknown> | null;
    /** True when the tracker is paused. */
    isPaused: boolean;
    /** When the tracker was paused. Null unless paused. */
    pausedAt: string | null;
    /** When the tracker last produced an alert. Null until the first alert. */
    lastNotifiedAt: string | null;
    /** When the tracker was created. */
    createdAt: string;
    /** When the tracker was last updated. */
    updatedAt: string | null;
    /** The monitor this tracker belongs to. Absent for standalone trackers. */
    monitorId?: string | undefined;
    /** Email deliveries in the current billing period. */
    emailDeliveryCount: number;
    /** Webhook deliveries in the current billing period. */
    webhookDeliveryCount: number;
    /** Slack deliveries in the current billing period. */
    slackDeliveryCount: number;
}
