// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TrackerListResponse {
    /** All trackers for the account, newest first. */
    trackers: Arcmira.Tracker[];
    /** Number of trackers returned. */
    count: number;
}
