// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TranscriptionListResponse {
    /** Your most recent requests, newest first: 20 without a filter, 5 when filtered to one video. */
    requests: TranscriptionListResponse.Requests.Item[];
}

export namespace TranscriptionListResponse {
    export type Requests = Requests.Item[];

    export namespace Requests {
        export interface Item extends Arcmira.TranscriptionRequest {
            /** Video title for display. Null when unknown. */
            title: string | null;
        }
    }
}
