// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TranscriptFailed {
    quality: TranscriptFailed.Quality;
    video_id: string;
    job: Arcmira.TranscriptJob;
    /** The failed purchase in brief: job.status and job.error. */
    last_attempt: TranscriptFailed.LastAttempt;
    /** What to do next: read again with retry=true to buy the video again, or wait while the refund settles. */
    note: string;
}

export namespace TranscriptFailed {
    export const Quality = {
        Premium: "premium",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];

    /**
     * The failed purchase in brief: job.status and job.error.
     */
    export interface LastAttempt {
        /** How the last purchase ended: failed, refunded (the charge was returned), or refund_pending (the refund is still settling). */
        status: LastAttempt.Status;
        /** Why it failed. */
        error: string;
    }

    export namespace LastAttempt {
        /** How the last purchase ended: failed, refunded (the charge was returned), or refund_pending (the refund is still settling). */
        export const Status = {
            Failed: "failed",
            RefundPending: "refund_pending",
            Refunded: "refunded",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
