// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TranscriptRequestSubmitResponse {
    job: Arcmira.TranscriptJob;
    /** True when a request for this video already existed (in flight or ready) and was returned instead of creating a new one. */
    existing: boolean;
}
