// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TranscriptPending {
    quality: TranscriptPending.Quality;
    video_id: string;
    job: Arcmira.TranscriptJob;
}

export namespace TranscriptPending {
    export const Quality = {
        Premium: "premium",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
