// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../index.js";

export interface TranscriptPurchaseQuote {
    video_id: string;
    duration_seconds: number;
    billing_scope: TranscriptPurchaseQuote.BillingScope;
    owned: boolean;
    eligible: boolean;
    quote: Arcmira.TranscriptQuote;
    charge: TranscriptPurchaseQuote.Charge;
    credits_per_row: number;
    max_on_demand_cents: number;
    on_demand_cents_per_unit: number;
    prepare_url: string;
    refund_policy: string;
}

export namespace TranscriptPurchaseQuote {
    export const BillingScope = {
        FullVideo: "full_video",
    } as const;
    export type BillingScope = (typeof BillingScope)[keyof typeof BillingScope];

    export interface Charge {
        unit: Charge.Unit;
        amount: number;
    }

    export namespace Charge {
        export const Unit = {
            Rows: "rows",
            Credits: "credits",
        } as const;
        export type Unit = (typeof Unit)[keyof typeof Unit];
    }
}
