// This file was auto-generated by Fern from our API Definition.

/**
 * A Premium transcript job with its processing state, charge and URL for reading the transcript again.
 */
export interface TranscriptJob {
    /** Transcription request id (UUID). */
    id: string;
    /** YouTube video id (11 characters). */
    video_id: string;
    /** Coarse outcome: pending until the Premium transcript is servable (ready), the job failed, or it was refunded. */
    state: TranscriptJob.State;
    /** Request status. Values: queued (accepted; audio download not started), downloading (fetching the video audio), transcribing (premium speech-to-text is running), analyzing (entity/commercial analysis is running), complete (premium transcript is servable via GET /v1/transcripts/{video_id}), failed (rejected intent, or a legacy request needing accounting review), refund_pending (refund transaction must still complete), refunded (terminal failure; the charged rows were returned and the unlock this request granted was revoked). */
    status: TranscriptJob.Status;
    /** User-facing stage: downloading folds into transcribing. Values: queued (waiting to start), transcribing (downloading or transcribing), analyzing (analysis running). Null for terminal statuses and refund_pending. */
    stage: TranscriptJob.Stage | null;
    /** What the job charged. Absent only on legacy requests. */
    charge?: TranscriptJob.Charge | undefined;
    /** Estimated seconds until completion, re-derived from live pipeline telemetry on every poll. Only present while the request is in flight; absent on refund_pending, which has no completion ETA. */
    eta_seconds?: number | undefined;
    /** Seconds to sleep before the next poll (also sent as the Retry-After header). Only present while the request is in flight. */
    next_poll_seconds?: number | undefined;
    /** Failure reason. Only present when state is failed or refunded, or status is refund_pending. */
    error?: string | undefined;
    /** True when the charge was returned. Only present when state is failed or refunded, or status is refund_pending (false until the refund lands). */
    refunded?: boolean | undefined;
    /** When the request was submitted. */
    created_at: string;
    /** When the request reached a terminal status. Absent while in flight. */
    completed_at?: string | undefined;
    /** Absolute URL to read again for this job: GET /v1/transcripts/{video_id}?quality=premium, which answers 202 while it transcribes, 200 ready once it is done, and 200 failed if it failed. */
    status_url: string;
}

export namespace TranscriptJob {
    /** Coarse outcome: pending until the Premium transcript is servable (ready), the job failed, or it was refunded. */
    export const State = {
        Pending: "pending",
        Ready: "ready",
        Failed: "failed",
        Refunded: "refunded",
    } as const;
    export type State = (typeof State)[keyof typeof State];
    /** Request status. Values: queued (accepted; audio download not started), downloading (fetching the video audio), transcribing (premium speech-to-text is running), analyzing (entity/commercial analysis is running), complete (premium transcript is servable via GET /v1/transcripts/{video_id}), failed (rejected intent, or a legacy request needing accounting review), refund_pending (refund transaction must still complete), refunded (terminal failure; the charged rows were returned and the unlock this request granted was revoked). */
    export const Status = {
        Queued: "queued",
        Downloading: "downloading",
        Transcribing: "transcribing",
        Analyzing: "analyzing",
        Complete: "complete",
        Failed: "failed",
        RefundPending: "refund_pending",
        Refunded: "refunded",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** User-facing stage: downloading folds into transcribing. Values: queued (waiting to start), transcribing (downloading or transcribing), analyzing (analysis running). Null for terminal statuses and refund_pending. */
    export const Stage = {
        Queued: "queued",
        Transcribing: "transcribing",
        Analyzing: "analyzing",
    } as const;
    export type Stage = (typeof Stage)[keyof typeof Stage];

    /**
     * What the job charged. Absent only on legacy requests.
     */
    export interface Charge {
        unit: Charge.Unit;
        /** Credits this job charged. 0 when a prior unlock made it free. */
        amount: number;
        /** Where the credits came from. included is the plan's credits, on_demand is the on-demand budget, mixed is both. Present once the job is funded. */
        from?: Charge.From | undefined;
    }

    export namespace Charge {
        export const Unit = {
            Credits: "credits",
        } as const;
        export type Unit = (typeof Unit)[keyof typeof Unit];
        /** Where the credits came from. included is the plan's credits, on_demand is the on-demand budget, mixed is both. Present once the job is funded. */
        export const From = {
            Included: "included",
            OnDemand: "on_demand",
            Mixed: "mixed",
        } as const;
        export type From = (typeof From)[keyof typeof From];
    }
}
