// This file was auto-generated by Fern from our API Definition.

export interface TranscriptPreparationRequired {
    quality: TranscriptPreparationRequired.Quality;
    video_id: string;
    /** Null when the video has no known duration or is longer than 12 hours; the POST refuses it for the same reason. */
    quote: TranscriptPreparationRequired.Quote | null;
    /** The one request that prepares Premium from included credits and moves no money. */
    action: TranscriptPreparationRequired.Action;
    /** The most recent failed or refunded purchase of this video, when there is one. */
    last_attempt?: TranscriptPreparationRequired.LastAttempt | undefined;
}

export namespace TranscriptPreparationRequired {
    export const Quality = {
        Premium: "premium",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];

    /**
     * Null when the video has no known duration or is longer than 12 hours; the POST refuses it for the same reason.
     */
    export interface Quote {
        /** Whole-video row-equivalent price. 0 when a prior unlock makes it free. */
        rows: number;
        charge: Quote.Charge;
        /** False when the account cannot buy right now; the POST then answers with the reason. */
        eligible: boolean;
        /** On-demand money in whole cents the purchase would need. 0 means included credits cover it. */
        max_on_demand_cents: number;
    }

    export namespace Quote {
        export interface Charge {
            unit: Charge.Unit;
            /** Credits the purchase would charge. */
            amount: number;
            /** Where those credits would come from at the current balance. */
            from: Charge.From;
        }

        export namespace Charge {
            export const Unit = {
                Credits: "credits",
            } as const;
            export type Unit = (typeof Unit)[keyof typeof Unit];
            /** Where those credits would come from at the current balance. */
            export const From = {
                Included: "included",
                OnDemand: "on_demand",
                Mixed: "mixed",
            } as const;
            export type From = (typeof From)[keyof typeof From];
        }
    }

    /**
     * The one request that prepares Premium from included credits and moves no money.
     */
    export interface Action {
        method: Action.Method;
        url: string;
        body: Action.Body;
    }

    export namespace Action {
        export const Method = {
            Post: "POST",
        } as const;
        export type Method = (typeof Method)[keyof typeof Method];

        export interface Body {
            video_id: string;
        }
    }

    /**
     * The most recent failed or refunded purchase of this video, when there is one.
     */
    export interface LastAttempt {
        status: string;
        error: string;
    }
}
