// This file was auto-generated by Fern from our API Definition.

/**
 * What a transcript request that names no parameter of its own receives.
 */
export interface TranscriptSettings {
    /** Default transcript quality. Platform default: captions. */
    quality: TranscriptSettings.Quality;
    /** Default comma-separated caption language priority list, tried in order. Platform default: en. */
    language: string;
    /** Default for the timestamps parameter. Platform default: true, which returns lines[]. */
    timestamps: boolean;
}

export namespace TranscriptSettings {
    /** Default transcript quality. Platform default: captions. */
    export const Quality = {
        Captions: "captions",
        Premium: "premium",
    } as const;
    export type Quality = (typeof Quality)[keyof typeof Quality];
}
