// This file was auto-generated by Fern from our API Definition.

export interface TranscriptVideo {
    /** YouTube video id (11 characters). */
    id: string;
    /** Video title. Empty when we could not read it. */
    title: string;
    /** YouTube channel id of the source channel. */
    channel_id: string | null;
    channel_name: string | null;
    /** Publish timestamp. Cite it as the date of anything you quote. */
    published_at: string | null;
    /** Video length in seconds. Null when unknown, which also means the credit estimate was unknown. */
    duration_seconds: number | null;
    /** Canonical YouTube watch URL. */
    watch_url: string;
}
