// This file was auto-generated by Fern from our API Definition.

export interface VideoMergeSubmittedResponse {
    /** The stored pending merge. */
    merge: VideoMergeSubmittedResponse.Merge;
}

export namespace VideoMergeSubmittedResponse {
    /**
     * The stored pending merge.
     */
    export interface Merge {
        /** Pending row id. Withdraw it with DELETE /v1/transcripts/{video_id}/merges/{id}. */
        id: number;
        /** YouTube video id (11 characters). */
        videoId: string;
        /** The name as it appears in the video. */
        sourceName: string;
        /** Raw integer entity id the name refers to. */
        targetEntityId: number;
        /** Respelling applied to the transcript text. Null when none. */
        replaceWith: string | null;
        /** Review status. Always pending on submit. */
        status: Merge.Status;
    }

    export namespace Merge {
        /** Review status. Always pending on submit. */
        export const Status = {
            Pending: "pending",
            Approved: "approved",
            Rejected: "rejected",
            Reverted: "reverted",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
