// This file was auto-generated by Fern from our API Definition.

/**
 * For issue_type wrong_classification: the commercial class the result should carry.
 */
export interface WrongClassificationChange {
    /** The correct commercial class. Values: sponsored (an ad-style promotion heard at that moment: a paid sponsor read, promo code, affiliate plug, thanks for supplied goods or venue, or a show promoting its own product as an ad), organic (an unpaid personal recommendation), mention (a neutral commercial mention). */
    class?: WrongClassificationChange.Class | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace WrongClassificationChange {
    /** The correct commercial class. Values: sponsored (an ad-style promotion heard at that moment: a paid sponsor read, promo code, affiliate plug, thanks for supplied goods or venue, or a show promoting its own product as an ad), organic (an unpaid personal recommendation), mention (a neutral commercial mention). */
    export const Class = {
        Sponsored: "sponsored",
        Organic: "organic",
        Mention: "mention",
    } as const;
    export type Class = (typeof Class)[keyof typeof Class];
}
