// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "slug"
 *     }
 */
export interface GetOrganizationsRequest {
    /** The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it. */
    slug: string;
}
