// This file was auto-generated by Fern from our API Definition.

export const LookupEntitiesRequestType = {
    Person: "person",
    Organization: "organization",
    Product: "product",
    Topic: "topic",
    Channel: "channel",
} as const;
export type LookupEntitiesRequestType = (typeof LookupEntitiesRequestType)[keyof typeof LookupEntitiesRequestType];
