// This file was auto-generated by Fern from our API Definition.

/** The surface making this call. The Arcmira MCP server sends mcp-tool so every unlock link in a gate attributes to the directory install. Omit from your own client. */
export const MomentumEntitiesRequestSrc = {
    McpTool: "mcp-tool",
} as const;
export type MomentumEntitiesRequestSrc = (typeof MomentumEntitiesRequestSrc)[keyof typeof MomentumEntitiesRequestSrc];
