// This file was auto-generated by Fern from our API Definition.

/** Restrict candidates to one type. Pass channel for a show and read best.youtube_channel_id. */
export const ResolveEntitiesRequestType = {
    Person: "person",
    Organization: "organization",
    Product: "product",
    Topic: "topic",
    Channel: "channel",
} as const;
export type ResolveEntitiesRequestType = (typeof ResolveEntitiesRequestType)[keyof typeof ResolveEntitiesRequestType];
