// This file was auto-generated by Fern from our API Definition.

export const SearchEntitiesRequestType = {
    Person: "person",
    Organization: "organization",
    Product: "product",
    Topic: "topic",
    Channel: "channel",
} as const;
export type SearchEntitiesRequestType = (typeof SearchEntitiesRequestType)[keyof typeof SearchEntitiesRequestType];
