// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "email",
 *         code: "code"
 *     }
 */
export interface VerifySignupRequest {
    /** The address the code was sent to. */
    email: string;
    /** The six digit code from the email. Ten minutes, five attempts, then a new send is required. */
    code: string;
}
