// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../index.js";

/**
 * @example
 *     {
 *         channel_id: "channel_id"
 *     }
 */
export interface CoverageChannelsRequest {
    /** YouTube channel id, the UC... form. */
    channel_id: string;
    /** The surface making this call. The Arcmira MCP server sends mcp-tool so every unlock link in a gate attributes to the directory install. Omit from your own client. */
    src?: Arcmira.CoverageChannelsRequestSrc;
}
