// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         channel_id: "channel_id"
 *     }
 */
export interface CoverageChannelsRequest {
    /** YouTube channel id, the UC... form. */
    channel_id: string;
}
