// This file was auto-generated by Fern from our API Definition.

export const ListRecommendationsRequestEntityType = {
    Person: "person",
    Organization: "organization",
    Product: "product",
    Topic: "topic",
    Channel: "channel",
} as const;
export type ListRecommendationsRequestEntityType =
    (typeof ListRecommendationsRequestEntityType)[keyof typeof ListRecommendationsRequestEntityType];
