// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
 *         entity_name: "entity_name",
 *         entity_type: "person"
 *     }
 */
export interface CreateTrackersRequest {
    /** One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation. */
    "Idempotency-Key"?: string;
    /** The exact name to watch, matched case-insensitively against analyzed media, so a tracker can exist before the entity is indexed. For a channel, the YouTube channel id (UC plus 22 characters), never a name: a channel name answers 400 id_required naming GET /v1/entities/resolve?q=...&type=channel and best.youtube_channel_id. Required on create. Creating a duplicate (same name, compared case-insensitively, and type) returns 409 tracker_already_exists with the existing tracker id in error.details.existing_id. */
    entity_name: string;
    /** Entity type of the tracked entity. Required on create. org is accepted for organization, and the tracker answers organization. */
    entity_type: CreateTrackersRequest.EntityType;
    /** Optional label shown in alerts and the dashboard. */
    display_name?: string;
    /** Per-tracker email delivery. Default true. */
    notify_email?: boolean;
    /** Per-tracker webhook delivery override. Paid plans only. */
    notify_webhook?: boolean;
    /** Per-tracker Slack delivery override. Paid plans only. */
    notify_slack?: boolean;
    /** Per-tracker webhook destination override (http/https). */
    webhook_url?: string;
    /** Per-tracker Slack channel override. */
    slack_channel_id?: string;
    /** Per-tracker Slack integration override. */
    slack_integration_id?: string;
    /** Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill. */
    person_match_mode?: CreateTrackersRequest.PersonMatchMode;
    /** Stored filter object. personMatchMode is also accepted here for person trackers. Other filter keys are retained; do not assume they change matching. */
    filters?: Record<string, unknown>;
}

export namespace CreateTrackersRequest {
    /** Entity type of the tracked entity. Required on create. org is accepted for organization, and the tracker answers organization. */
    export const EntityType = {
        Person: "person",
        Organization: "organization",
        Org: "org",
        Product: "product",
        Topic: "topic",
        Channel: "channel",
    } as const;
    export type EntityType = (typeof EntityType)[keyof typeof EntityType];
    /** Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill. */
    export const PersonMatchMode = {
        Mentions: "mentions",
        Appearances: "appearances",
        Both: "both",
    } as const;
    export type PersonMatchMode = (typeof PersonMatchMode)[keyof typeof PersonMatchMode];
}
