// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entityName: "entityName",
 *         entityType: "person"
 *     }
 */
export interface CreateTrackersRequest {
    /** Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation. */
    "Idempotency-Key"?: string;
    /** The entity name to resolve and watch. Required on create. Creating a duplicate (same name + type) returns 409 with the existingId. */
    entityName: string;
    /** Entity type of the tracked entity. Required on create. */
    entityType: CreateTrackersRequest.EntityType;
    /** Optional label shown in alerts and the dashboard. */
    displayName?: string;
    /** Per-tracker email delivery. Default true. */
    notifyEmail?: boolean;
    /** Per-tracker webhook delivery override. Paid plans only. */
    notifyWebhook?: boolean;
    /** Per-tracker Slack delivery override. Paid plans only. */
    notifySlack?: boolean;
    /** Per-tracker webhook destination override (http/https). */
    webhookUrl?: string;
    /** Per-tracker Slack channel override. */
    slackChannelId?: string;
    /** Per-tracker Slack integration override. */
    slackIntegrationId?: string;
    /** Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill. */
    personMatchMode?: CreateTrackersRequest.PersonMatchMode;
    /** Stored filter object. personMatchMode is also accepted here for person trackers. Other filter keys are retained; do not assume they change matching. */
    filters?: Record<string, unknown>;
}

export namespace CreateTrackersRequest {
    /** Entity type of the tracked entity. Required on create. */
    export const EntityType = {
        Person: "person",
        Organization: "organization",
        Product: "product",
        Topic: "topic",
        Channel: "channel",
    } as const;
    export type EntityType = (typeof EntityType)[keyof typeof EntityType];
    /** Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill. */
    export const PersonMatchMode = {
        Mentions: "mentions",
        Appearances: "appearances",
        Both: "both",
    } as const;
    export type PersonMatchMode = (typeof PersonMatchMode)[keyof typeof PersonMatchMode];
}
