// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteTrackersRequest {
    /** Tracker id, trk_ form. */
    id: string;
}
