// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateTrackersRequest {
    /** Tracker id, trk_ form. */
    id: string;
    /** Optional label shown in alerts and the dashboard. */
    displayName?: string;
    /** Per-tracker email delivery. Default true. */
    notifyEmail?: boolean;
    /** Per-tracker webhook delivery override. Paid plans only. */
    notifyWebhook?: boolean;
    /** Per-tracker Slack delivery override. Paid plans only. */
    notifySlack?: boolean;
    /** Per-tracker webhook destination override (http/https). */
    webhookUrl?: string;
    /** Per-tracker Slack channel override. */
    slackChannelId?: string;
    /** Per-tracker Slack integration override. */
    slackIntegrationId?: string;
    /** Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill. */
    personMatchMode?: UpdateTrackersRequest.PersonMatchMode;
    /** Stored filter object. personMatchMode is also accepted here for person trackers. Other filter keys are retained; do not assume they change matching. */
    filters?: Record<string, unknown>;
    /** Pause or resume the tracker. Paused trackers stop producing alerts; there is no backfill for the paused window. */
    paused?: boolean;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace UpdateTrackersRequest {
    /** Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill. */
    export const PersonMatchMode = {
        Mentions: "mentions",
        Appearances: "appearances",
        Both: "both",
    } as const;
    export type PersonMatchMode = (typeof PersonMatchMode)[keyof typeof PersonMatchMode];
}
