// This file was auto-generated by Fern from our API Definition.

/** Person relationship lens: guest appearances or inbound mentions. */
export const ListAppearancesRequestMode = {
    Appearances: "appearances",
    Mentions: "mentions",
} as const;
export type ListAppearancesRequestMode = (typeof ListAppearancesRequestMode)[keyof typeof ListAppearancesRequestMode];
