// This file was auto-generated by Fern from our API Definition.

/** Sort direction. Default desc. */
export const ListAppearancesRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListAppearancesRequestOrder =
    (typeof ListAppearancesRequestOrder)[keyof typeof ListAppearancesRequestOrder];
