"""Generate CLI schema and reference from the checked-in public contract."""
import json
import runpy
from pathlib import Path

root = Path(__file__).resolve().parents[1]
resolve = runpy.run_path(str(root / 'scripts/prepare-openapi.py'))['resolve']
doc = json.loads((root / 'fern/openapi.json').read_text())
sdk = json.loads((root / 'fern/openapi.sdk.json').read_text())

def field(name, where, schema, required, description=''):
    schema = resolve(doc, schema)
    kind = schema.get('type', 'object')
    if isinstance(kind, list): kind = '|'.join(kind)
    if kind == 'array': kind = str(schema.get('items', {}).get('type', 'object')) + '[]'
    if 'minimum' in schema or 'maximum' in schema:
        kind += f" {schema.get('minimum', '')}..{schema.get('maximum', '')}"
    return dict(name=name, **{'in': where}, required=required, type=kind,
                **({'enum': schema['enum']} if 'enum' in schema else {}),
                **({'description': description or schema['description']} if description or 'description' in schema else {}))

operations=[]
reference=['# API reference', '', 'Generated from `fern/openapi.json` and the public SDK overlay. Run `python3 scripts/build-reference.py`.', '',
           'Transcript reads return `state: ready` or `state: pending`. TypeScript uses `.withRawResponse()` for HTTP status and headers. Python uses `.with_raw_response`.', '',
           'Preparation requires a persisted Idempotency-Key and max_rows. max_on_demand_cents defaults to zero. Retry a lost response with the same key and identical input.', '']
for path, methods in doc['paths'].items():
    for method, op in methods.items():
        if method not in {'get','post','put','patch','delete'}: continue
        params=[field(p['name'],p['in'],p.get('schema',{}),p.get('required',False),p.get('description','')) for p in op.get('parameters',[])]
        body_schema=resolve(doc,resolve(doc,op.get('requestBody',{})).get('content',{}).get('application/json',{}).get('schema',{}))
        body=[field(k,'body',v,k in body_schema.get('required',[])) for k,v in body_schema.get('properties',{}).items()] or None
        operations.append(dict(operationId=op['operationId'],method=method.upper(),path=path,summary=op.get('summary',''),params=params,body=body))
        if path not in sdk['paths'] or method not in sdk['paths'][path]: continue
        op = sdk['paths'][path][method]
        params = [field(p['name'], p['in'], p.get('schema', {}), p.get('required', False), p.get('description', '')) for p in op.get('parameters', [])]
        body_schema=resolve(sdk,resolve(sdk,op.get('requestBody',{})).get('content',{}).get('application/json',{}).get('schema',{}))
        body=[field(k,'body',v,k in body_schema.get('required',[])) for k,v in body_schema.get('properties',{}).items()] or None
        group=op.get('x-fern-sdk-group-name', op.get('tags', ['api'])[0].lower()); group='.'.join(group) if isinstance(group,list) else group
        name=op.get('x-fern-sdk-method-name',op['operationId'])
        reference += [f'## {group}.{name}', '', f'`{method.upper()} {path}`', '', op.get('description',op.get('summary','')), '']
        if params or body:
            reference += ['| Field | Location | Required | Type |','|---|---|---|---|']
            reference += [f"| `{p['name']}` | {p['in']} | {'yes' if p['required'] else 'no'} | {p['type'].replace('|',' or ')} |" for p in params+(body or [])]
            reference += ['']
(root/'reference.md').write_text('\n'.join(reference)+'\n')
if (root/'cli').exists():
    text='// Generated by scripts/build-reference.py from the public OpenAPI input. Do not edit.\n\n'
    text+='export type Field = { name: string; in: string; required: boolean; type: string; enum?: unknown[]; description?: string };\n'
    text+='export type Operation = { operationId: string; method: string; path: string; summary: string; params: Field[]; body: Field[] | null };\n\n'
    text+='export const OPERATIONS: Operation[] = '+'[\n' + '\n'.join('  ' + json.dumps(op, separators=(',', ':'), ensure_ascii=False) + ',' for op in operations) + '\n];\n'
    (root/'cli/operations.ts').write_text(text)
