// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../index.js";

/**
 * @example
 *     {
 *         video_id: "video_id"
 *     }
 */
export interface GetTranscriptsRequest {
    /** YouTube video id, 11 characters. */
    video_id: string;
    /** captions reads creator or automatic captions at 1 row per started 15 minutes. premium is one read: an owned transcript returns 200 state ready at zero rows; otherwise the read buys the whole video within the account's plan and on-demand budget (included credits first, then on-demand money up to the account limit) and returns 202 state pending with the job until it is ready. 402 quota_exceeded or spend_limit_exceeded and 403 paid_plan_required carry the price in quote. It never substitutes captions. Default captions unless changed in account settings. */
    quality?: Arcmira.GetTranscriptsRequestQuality;
    /** Comma-separated caption language priority list, at most 5, tried in order (e.g. "de,en"). Use asr for the first automatic track and asr-<code> for a specific one. Default en. languages[] in the response lists every track the video offers. */
    language?: string;
    /** false returns paragraphs[] of { start, text, speaker? } instead of lines[], for reading rather than citing. Default true. */
    timestamps?: boolean;
    /** Window start in seconds from the beginning of the video. Send start and end together. On captions the window bills only its own started 15-minute blocks; on Premium it trims an already purchased transcript; this GET does not charge. */
    start?: number | null;
    /** Window end in seconds, greater than start and no greater than the video duration. Send start and end together. */
    end?: number | null;
    /** Captions only; Premium with refresh=true returns invalid_query. Refetch the caption track from YouTube instead of serving the stored copy. Available only for videos outside our index; a pipeline-owned video refuses it with invalid_query. */
    refresh?: boolean;
}
