// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         video_id: "video_id"
 *     }
 */
export interface QuoteTranscriptsRequest {
    /** YouTube video id, 11 characters. */
    video_id: string;
}
