// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         max_rows: 1
 *     }
 */
export interface RequestTranscriptsRequest {
    /** Persist a unique key and the exact request before sending a logical mutation. A retry returns its stored response with Idempotency-Replayed: true. A changed intent under a finalized key returns 409 idempotency_conflict. Keys belong to the authenticated owner, credential and mutation domain. Current authorization still applies. Receipts have no general 24-hour expiry; signing-secret recovery alone expires after 24 hours or when the secret is displaced. */
    "Idempotency-Key": string;
    /** Maximum new monetary on-demand charge in cents. Omit to authorize none. */
    max_on_demand_cents?: number;
    /** Maximum whole-video rows authorized. Credit mode charges four credits per row. Required even when submitting without a quote. */
    max_rows: number;
    /** YouTube video id (11 characters). Either videoId or url is required. */
    videoId?: string;
    /** A YouTube watch/short/live URL. Either videoId or url is required. */
    url?: string;
}
