// This file was auto-generated by Fern from our API Definition.

import type * as Arcmira from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface StatusTranscriptsRequest {
    /** Transcription request id, the UUID POST /v1/transcriptions returned. */
    id: string;
    /** The surface making this call. The Arcmira MCP server sends mcp-tool so every unlock link in a gate attributes to the directory install. Omit from your own client. */
    src?: Arcmira.StatusTranscriptsRequestSrc;
}
