// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../core/requestBody.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Arcmira from "../../../../../index.js";

export declare namespace EntitiesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EntitiesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EntitiesClient.Options>;

    constructor(options: EntitiesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Follows each entity ({ entity_ids: ["ent_..."] }) and each exact name ({ names: [{ name, type }] }) in the monitor: the monitor account's existing tracker for the entity or name (compared case-insensitively) is reused, else a tracker is created under the monitor's account (the team owner on a team monitor) for the canonical entity (a merged id follows its redirect) or the name as given, then the trackers are attached, all in one write. Use names for something not yet indexed; a channel is named by its YouTube channel id, and a channel name answers 400 id_required. Attached trackers use the monitor's delivery settings. Supply 1 to 90 ids and names together; duplicates count once. Each gets one result, ids first then names, in request order; a names result carries name and type in place of entity_id. An id that cannot be followed comes back with attached: false and a reason (entity_not_found, entity_type_not_trackable, tracker_limit_reached, tracked_in_another_monitor) while the rest still attach; a tracker already in another monitor is left there and named in current_monitor_id. Requires the monitors:write and trackers:write scopes.
     *
     * @param {Arcmira.monitors.AddEntitiesRequest} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.ConflictError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.monitors.entities.add({
     *         "Idempotency-Key": "8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
     *         id: "id"
     *     })
     */
    public add(
        request: Arcmira.monitors.AddEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Arcmira.MonitorAddEntitiesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__add(request, requestOptions));
    }

    private async __add(
        request: Arcmira.monitors.AddEntitiesRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Arcmira.MonitorAddEntitiesResponse>> {
        const { id, "Idempotency-Key": idempotencyKey, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Idempotency-Key": idempotencyKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ArcmiraEnvironment.Default,
                `v1/monitors/${core.url.encodePathParam(id)}/entities`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Arcmira.MonitorAddEntitiesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Arcmira.BadRequestError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 401:
                    throw new Arcmira.UnauthorizedError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 403:
                    throw new Arcmira.ForbiddenError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 404:
                    throw new Arcmira.NotFoundError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 409:
                    throw new Arcmira.ConflictError(_response.error.body as Arcmira.Error_, _response.rawResponse);
                case 429:
                    throw new Arcmira.TooManyRequestsError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Arcmira.InternalServerError(
                        _response.error.body as Arcmira.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ArcmiraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/monitors/{id}/entities");
    }
}
