// This file was auto-generated by Fern from our API Definition.

import { ChannelsClient } from "./api/resources/channels/client/Client.js";
import { CorrectionsClient } from "./api/resources/corrections/client/Client.js";
import { EntitiesClient } from "./api/resources/entities/client/Client.js";
import { FeedbackClient } from "./api/resources/feedback/client/Client.js";
import { HealthClient } from "./api/resources/health/client/Client.js";
import { MeClient } from "./api/resources/me/client/Client.js";
import { MentionsClient } from "./api/resources/mentions/client/Client.js";
import { MonitorsClient } from "./api/resources/monitors/client/Client.js";
import { OrganizationsClient } from "./api/resources/organizations/client/Client.js";
import { PeopleClient } from "./api/resources/people/client/Client.js";
import { ProductsClient } from "./api/resources/products/client/Client.js";
import { RecommendationsClient } from "./api/resources/recommendations/client/Client.js";
import { TeamClient } from "./api/resources/team/client/Client.js";
import { TopicsClient } from "./api/resources/topics/client/Client.js";
import { TrackersClient } from "./api/resources/trackers/client/Client.js";
import { TranscriptionsClient } from "./api/resources/transcriptions/client/Client.js";
import { TranscriptsClient } from "./api/resources/transcripts/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace ArcmiraClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ArcmiraClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ArcmiraClient.Options>;
    protected _health: HealthClient | undefined;
    protected _me: MeClient | undefined;
    protected _entities: EntitiesClient | undefined;
    protected _mentions: MentionsClient | undefined;
    protected _recommendations: RecommendationsClient | undefined;
    protected _feedback: FeedbackClient | undefined;
    protected _transcripts: TranscriptsClient | undefined;
    protected _channels: ChannelsClient | undefined;
    protected _people: PeopleClient | undefined;
    protected _topics: TopicsClient | undefined;
    protected _organizations: OrganizationsClient | undefined;
    protected _products: ProductsClient | undefined;
    protected _monitors: MonitorsClient | undefined;
    protected _trackers: TrackersClient | undefined;
    protected _team: TeamClient | undefined;
    protected _transcriptions: TranscriptionsClient | undefined;
    protected _corrections: CorrectionsClient | undefined;

    constructor(options: ArcmiraClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get health(): HealthClient {
        return (this._health ??= new HealthClient(this._options));
    }

    public get me(): MeClient {
        return (this._me ??= new MeClient(this._options));
    }

    public get entities(): EntitiesClient {
        return (this._entities ??= new EntitiesClient(this._options));
    }

    public get mentions(): MentionsClient {
        return (this._mentions ??= new MentionsClient(this._options));
    }

    public get recommendations(): RecommendationsClient {
        return (this._recommendations ??= new RecommendationsClient(this._options));
    }

    public get feedback(): FeedbackClient {
        return (this._feedback ??= new FeedbackClient(this._options));
    }

    public get transcripts(): TranscriptsClient {
        return (this._transcripts ??= new TranscriptsClient(this._options));
    }

    public get channels(): ChannelsClient {
        return (this._channels ??= new ChannelsClient(this._options));
    }

    public get people(): PeopleClient {
        return (this._people ??= new PeopleClient(this._options));
    }

    public get topics(): TopicsClient {
        return (this._topics ??= new TopicsClient(this._options));
    }

    public get organizations(): OrganizationsClient {
        return (this._organizations ??= new OrganizationsClient(this._options));
    }

    public get products(): ProductsClient {
        return (this._products ??= new ProductsClient(this._options));
    }

    public get monitors(): MonitorsClient {
        return (this._monitors ??= new MonitorsClient(this._options));
    }

    public get trackers(): TrackersClient {
        return (this._trackers ??= new TrackersClient(this._options));
    }

    public get team(): TeamClient {
        return (this._team ??= new TeamClient(this._options));
    }

    public get transcriptions(): TranscriptionsClient {
        return (this._transcriptions ??= new TranscriptionsClient(this._options));
    }

    public get corrections(): CorrectionsClient {
        return (this._corrections ??= new CorrectionsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
