// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as Arcmira from "../../../../../index.js";

export declare namespace RelatedClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class RelatedClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RelatedClient.Options>;

    constructor(options: RelatedClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * The topics that co-occur with this product in indexed media, with q/field/sort/order filtering. Signed cursor pagination: rows are in items, and next_cursor (null on the last page) feeds cursor. A token binds route, filters, caller and visibility; malformed or old tokens return invalid_cursor. Aggregate and display lists are live: changed ranks or deleted rows may shift later pages. total counts every matching row and limit is the page size applied.
     *
     * @param {Arcmira.products.TopicsRelatedRequest} request
     * @param {RelatedClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.products.related.topics({
     *         slug: "slug"
     *     })
     */
    public async topics(
        request: Arcmira.products.TopicsRelatedRequest,
        requestOptions?: RelatedClient.RequestOptions,
    ): Promise<core.Page<Arcmira.EntityTopicListResponse.Items.Item, Arcmira.EntityTopicListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Arcmira.products.TopicsRelatedRequest,
            ): Promise<core.WithRawResponse<Arcmira.EntityTopicListResponse>> => {
                const { slug, limit, cursor, q, field, sort, order, mode, is_appearance: isAppearance } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    q,
                    field,
                    sort,
                    order: order != null ? order : undefined,
                    mode: mode != null ? mode : undefined,
                    is_appearance: isAppearance != null ? isAppearance : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ArcmiraEnvironment.Default,
                        `v1/products/${core.url.encodePathParam(slug)}/topics`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Arcmira.EntityTopicListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Arcmira.BadRequestError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Arcmira.UnauthorizedError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 402:
                            throw new Arcmira.PaymentRequiredError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Arcmira.ForbiddenError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Arcmira.NotFoundError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Arcmira.TooManyRequestsError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Arcmira.InternalServerError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ArcmiraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/products/{slug}/topics",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Arcmira.EntityTopicListResponse.Items.Item, Arcmira.EntityTopicListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next_cursor != null &&
                !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
            },
        });
    }

    /**
     * The people that co-occur with this product in indexed media, with q/field/sort/order filtering. Signed cursor pagination: rows are in items, and next_cursor (null on the last page) feeds cursor. A token binds route, filters, caller and visibility; malformed or old tokens return invalid_cursor. Aggregate and display lists are live: changed ranks or deleted rows may shift later pages. total counts every matching row and limit is the page size applied.
     *
     * @param {Arcmira.products.PeopleRelatedRequest} request
     * @param {RelatedClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.products.related.people({
     *         slug: "slug"
     *     })
     */
    public async people(
        request: Arcmira.products.PeopleRelatedRequest,
        requestOptions?: RelatedClient.RequestOptions,
    ): Promise<core.Page<Arcmira.EntityPeopleListResponse.Items.Item, Arcmira.EntityPeopleListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Arcmira.products.PeopleRelatedRequest,
            ): Promise<core.WithRawResponse<Arcmira.EntityPeopleListResponse>> => {
                const { slug, limit, cursor, q, field, sort, order, mode, is_appearance: isAppearance } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    q,
                    field,
                    sort,
                    order: order != null ? order : undefined,
                    mode: mode != null ? mode : undefined,
                    is_appearance: isAppearance != null ? isAppearance : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ArcmiraEnvironment.Default,
                        `v1/products/${core.url.encodePathParam(slug)}/people`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Arcmira.EntityPeopleListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Arcmira.BadRequestError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Arcmira.UnauthorizedError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 402:
                            throw new Arcmira.PaymentRequiredError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Arcmira.ForbiddenError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Arcmira.NotFoundError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Arcmira.TooManyRequestsError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Arcmira.InternalServerError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ArcmiraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/products/{slug}/people",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Arcmira.EntityPeopleListResponse.Items.Item, Arcmira.EntityPeopleListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next_cursor != null &&
                !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
            },
        });
    }

    /**
     * The organizations that co-occur with this product in indexed media, with q/field/sort/order filtering. Signed cursor pagination: rows are in items, and next_cursor (null on the last page) feeds cursor. A token binds route, filters, caller and visibility; malformed or old tokens return invalid_cursor. Aggregate and display lists are live: changed ranks or deleted rows may shift later pages. total counts every matching row and limit is the page size applied.
     *
     * @param {Arcmira.products.OrganizationsRelatedRequest} request
     * @param {RelatedClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.products.related.organizations({
     *         slug: "slug"
     *     })
     */
    public async organizations(
        request: Arcmira.products.OrganizationsRelatedRequest,
        requestOptions?: RelatedClient.RequestOptions,
    ): Promise<core.Page<Arcmira.EntityOrganizationListResponse.Items.Item, Arcmira.EntityOrganizationListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Arcmira.products.OrganizationsRelatedRequest,
            ): Promise<core.WithRawResponse<Arcmira.EntityOrganizationListResponse>> => {
                const { slug, limit, cursor, q, field, sort, order, mode, is_appearance: isAppearance } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    q,
                    field,
                    sort,
                    order: order != null ? order : undefined,
                    mode: mode != null ? mode : undefined,
                    is_appearance: isAppearance != null ? isAppearance : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ArcmiraEnvironment.Default,
                        `v1/products/${core.url.encodePathParam(slug)}/organizations`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Arcmira.EntityOrganizationListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Arcmira.BadRequestError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Arcmira.UnauthorizedError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 402:
                            throw new Arcmira.PaymentRequiredError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Arcmira.ForbiddenError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Arcmira.NotFoundError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Arcmira.TooManyRequestsError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Arcmira.InternalServerError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ArcmiraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/products/{slug}/organizations",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Arcmira.EntityOrganizationListResponse.Items.Item, Arcmira.EntityOrganizationListResponse>(
            {
                response: dataWithRawResponse.data,
                rawResponse: dataWithRawResponse.rawResponse,
                hasNextPage: (response) =>
                    response?.next_cursor != null &&
                    !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
                getItems: (response) => response?.items ?? [],
                loadPage: (response) => {
                    return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
                },
            },
        );
    }

    /**
     * The products that co-occur with this product in indexed media, with q/field/sort/order filtering. Signed cursor pagination: rows are in items, and next_cursor (null on the last page) feeds cursor. A token binds route, filters, caller and visibility; malformed or old tokens return invalid_cursor. Aggregate and display lists are live: changed ranks or deleted rows may shift later pages. total counts every matching row and limit is the page size applied.
     *
     * @param {Arcmira.products.ProductsRelatedRequest} request
     * @param {RelatedClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.products.related.products({
     *         slug: "slug"
     *     })
     */
    public async products(
        request: Arcmira.products.ProductsRelatedRequest,
        requestOptions?: RelatedClient.RequestOptions,
    ): Promise<core.Page<Arcmira.EntityProductListResponse.Items.Item, Arcmira.EntityProductListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Arcmira.products.ProductsRelatedRequest,
            ): Promise<core.WithRawResponse<Arcmira.EntityProductListResponse>> => {
                const { slug, limit, cursor, q, field, sort, order, mode, is_appearance: isAppearance } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    q,
                    field,
                    sort,
                    order: order != null ? order : undefined,
                    mode: mode != null ? mode : undefined,
                    is_appearance: isAppearance != null ? isAppearance : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ArcmiraEnvironment.Default,
                        `v1/products/${core.url.encodePathParam(slug)}/products`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Arcmira.EntityProductListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Arcmira.BadRequestError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Arcmira.UnauthorizedError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 402:
                            throw new Arcmira.PaymentRequiredError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Arcmira.ForbiddenError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Arcmira.NotFoundError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Arcmira.TooManyRequestsError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Arcmira.InternalServerError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ArcmiraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/products/{slug}/products",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Arcmira.EntityProductListResponse.Items.Item, Arcmira.EntityProductListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next_cursor != null &&
                !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
            },
        });
    }

    /**
     * The channels that co-occur with this product in indexed media, with q/field/sort/order filtering. Signed cursor pagination: rows are in items, and next_cursor (null on the last page) feeds cursor. A token binds route, filters, caller and visibility; malformed or old tokens return invalid_cursor. Aggregate and display lists are live: changed ranks or deleted rows may shift later pages. total counts every matching row and limit is the page size applied.
     *
     * @param {Arcmira.products.ChannelsRelatedRequest} request
     * @param {RelatedClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Arcmira.BadRequestError}
     * @throws {@link Arcmira.UnauthorizedError}
     * @throws {@link Arcmira.PaymentRequiredError}
     * @throws {@link Arcmira.ForbiddenError}
     * @throws {@link Arcmira.NotFoundError}
     * @throws {@link Arcmira.TooManyRequestsError}
     * @throws {@link Arcmira.InternalServerError}
     * @throws {@link errors.ArcmiraError}
     * @throws {@link errors.ArcmiraTimeoutError}
     *
     * @example
     *     await client.products.related.channels({
     *         slug: "slug"
     *     })
     */
    public async channels(
        request: Arcmira.products.ChannelsRelatedRequest,
        requestOptions?: RelatedClient.RequestOptions,
    ): Promise<core.Page<Arcmira.EntityChannelListResponse.Items.Item, Arcmira.EntityChannelListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Arcmira.products.ChannelsRelatedRequest,
            ): Promise<core.WithRawResponse<Arcmira.EntityChannelListResponse>> => {
                const { slug, limit, cursor, q, field, sort, order, mode, is_appearance: isAppearance } = request;
                const _queryParams: Record<string, unknown> = {
                    limit,
                    cursor,
                    q,
                    field,
                    sort,
                    order: order != null ? order : undefined,
                    mode: mode != null ? mode : undefined,
                    is_appearance: isAppearance != null ? isAppearance : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.ArcmiraEnvironment.Default,
                        `v1/products/${core.url.encodePathParam(slug)}/channels`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Arcmira.EntityChannelListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new Arcmira.BadRequestError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new Arcmira.UnauthorizedError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 402:
                            throw new Arcmira.PaymentRequiredError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new Arcmira.ForbiddenError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new Arcmira.NotFoundError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new Arcmira.TooManyRequestsError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new Arcmira.InternalServerError(
                                _response.error.body as Arcmira.Error_,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.ArcmiraError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/products/{slug}/channels",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<Arcmira.EntityChannelListResponse.Items.Item, Arcmira.EntityChannelListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next_cursor != null &&
                !(typeof response?.next_cursor === "string" && response?.next_cursor === ""),
            getItems: (response) => response?.items ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.next_cursor));
            },
        });
    }
}
