// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         video_id: "video_id",
 *         id: "id"
 *     }
 */
export interface WithdrawEditsRequest {
    /** YouTube video id, 11 characters. */
    video_id: string;
    /** The pending row id, as result.id of the response that accepted it. */
    id: string;
}
