// This file was auto-generated by Fern from our API Definition.

/** Sort direction. Default desc. */
export const ListGuestsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListGuestsRequestOrder = (typeof ListGuestsRequestOrder)[keyof typeof ListGuestsRequestOrder];
