// This file was auto-generated by Fern from our API Definition.

/** Person relationship lens: guest appearances or inbound mentions. */
export const ListGuestsRequestMode = {
    Appearances: "appearances",
    Mentions: "mentions",
} as const;
export type ListGuestsRequestMode = (typeof ListGuestsRequestMode)[keyof typeof ListGuestsRequestMode];
